--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("game_res/cards/mj_back.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(5)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setVisible(false)
Image_back:setPosition(0.0000, 9.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setSize({width = 75.0000, height = 110.0000})
layout:setLeftMargin(-37.5000)
layout:setRightMargin(-37.5000)
layout:setTopMargin(-64.0002)
layout:setBottomMargin(-45.9998)
Node:addChild(Image_back)

--Create Image_card
local Image_card = ccui.ImageView:create()
Image_card:ignoreContentAdaptWithSize(false)
Image_card:loadTexture("game_res/cards/mj_face.png",0)
Image_card:setScale9Enabled(true)
Image_card:setCapInsets({x = 19, y = 29, width = 37, height = 52})
Image_card:setLayoutComponentEnabled(true)
Image_card:setName("Image_card")
Image_card:setTag(4)
Image_card:setCascadeColorEnabled(true)
Image_card:setCascadeOpacityEnabled(true)
Image_card:setPosition(0.0000, 7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_card)
layout:setSize({width = 75.0000, height = 110.0000})
layout:setLeftMargin(-37.5000)
layout:setRightMargin(-37.5000)
layout:setTopMargin(-62.0000)
layout:setBottomMargin(-48.0000)
Node:addChild(Image_card)

--Create Image_ting
local Image_ting = ccui.ImageView:create()
Image_ting:ignoreContentAdaptWithSize(false)
Image_ting:loadTexture("game_res/desk/tingtubiao.png",0)
Image_ting:setLayoutComponentEnabled(true)
Image_ting:setName("Image_ting")
Image_ting:setTag(244)
Image_ting:setCascadeColorEnabled(true)
Image_ting:setCascadeOpacityEnabled(true)
Image_ting:setVisible(false)
Image_ting:setPosition(49.0041, 99.0329)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_ting)
layout:setPositionPercentX(0.6534)
layout:setPositionPercentY(0.9003)
layout:setPercentWidth(0.7867)
layout:setPercentHeight(0.4182)
layout:setSize({width = 59.0000, height = 46.0000})
layout:setLeftMargin(19.5041)
layout:setRightMargin(-3.5041)
layout:setTopMargin(-12.0329)
layout:setBottomMargin(76.0329)
Image_card:addChild(Image_ting)

--Create cardImg
local cardImg = ccui.ImageView:create()
cardImg:ignoreContentAdaptWithSize(false)
cardImg:loadTexture("game_res/cards/mj_1.png",0)
cardImg:setLayoutComponentEnabled(true)
cardImg:setName("cardImg")
cardImg:setTag(6)
cardImg:setCascadeColorEnabled(true)
cardImg:setCascadeOpacityEnabled(true)
cardImg:setPosition(36.0000, 40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cardImg)
layout:setPositionPercentX(0.4800)
layout:setPositionPercentY(0.3636)
layout:setPercentWidth(0.6400)
layout:setPercentHeight(0.6273)
layout:setSize({width = 48.0000, height = 69.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(15.0000)
layout:setTopMargin(35.5000)
layout:setBottomMargin(5.5000)
Image_card:addChild(cardImg)

--Create Image_card_1
local Image_card_1 = ccui.ImageView:create()
Image_card_1:ignoreContentAdaptWithSize(false)
Image_card_1:loadTexture("game_res/cards/mj_face.png",0)
Image_card_1:setScale9Enabled(true)
Image_card_1:setCapInsets({x = 19, y = 29, width = 37, height = 52})
Image_card_1:setLayoutComponentEnabled(true)
Image_card_1:setName("Image_card_1")
Image_card_1:setTag(58)
Image_card_1:setCascadeColorEnabled(true)
Image_card_1:setCascadeOpacityEnabled(true)
Image_card_1:setVisible(false)
Image_card_1:setPosition(0.0000, 4.9557)
Image_card_1:setScaleY(-1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_card_1)
layout:setSize({width = 75.0000, height = 110.0000})
layout:setLeftMargin(-37.5000)
layout:setRightMargin(-37.5000)
layout:setTopMargin(-59.9557)
layout:setBottomMargin(-50.0443)
Node:addChild(Image_card_1)

--Create cardImg_1
local cardImg_1 = ccui.ImageView:create()
cardImg_1:ignoreContentAdaptWithSize(false)
cardImg_1:loadTexture("game_res/cards/mj_1.png",0)
cardImg_1:setLayoutComponentEnabled(true)
cardImg_1:setName("cardImg_1")
cardImg_1:setTag(59)
cardImg_1:setCascadeColorEnabled(true)
cardImg_1:setCascadeOpacityEnabled(true)
cardImg_1:setPosition(36.0000, 40.0003)
cardImg_1:setScaleY(-1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cardImg_1)
layout:setPositionPercentX(0.4800)
layout:setPositionPercentY(0.3636)
layout:setPercentWidth(0.6400)
layout:setPercentHeight(0.6273)
layout:setSize({width = 48.0000, height = 69.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(15.0000)
layout:setTopMargin(35.4997)
layout:setBottomMargin(5.5003)
Image_card_1:addChild(cardImg_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(10)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(9.0002)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Image_back)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Image_back)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Image_back)

--Create VisibleForFrameTimeline
local VisibleForFrameTimeline = ccs.Timeline:create()

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

result['animation']:addTimeline(VisibleForFrameTimeline)
VisibleForFrameTimeline:setNode(Image_back)

--Create VisibleForFrameTimeline
local VisibleForFrameTimeline = ccs.Timeline:create()

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

result['animation']:addTimeline(VisibleForFrameTimeline)
VisibleForFrameTimeline:setNode(Image_card)

--Create VisibleForFrameTimeline
local VisibleForFrameTimeline = ccs.Timeline:create()

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(false)
localFrame:setVisible(false)
VisibleForFrameTimeline:addFrame(localFrame)

localFrame = ccs.VisibleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(false)
localFrame:setVisible(true)
VisibleForFrameTimeline:addFrame(localFrame)

result['animation']:addTimeline(VisibleForFrameTimeline)
VisibleForFrameTimeline:setNode(Image_card_1)
--Create Animation List
local animation0 = {name="animation0", startIndex=1, endIndex=1}
result['animation']:addAnimationInfo(animation0)
local animation2 = {name="animation2", startIndex=10, endIndex=10}
result['animation']:addAnimationInfo(animation2)
local animation1 = {name="animation1", startIndex=5, endIndex=5}
result['animation']:addAnimationInfo(animation1)

result['root'] = Node
return result;
end

return Result

