--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_tag
local Image_tag = ccui.ImageView:create()
Image_tag:ignoreContentAdaptWithSize(false)
Image_tag:loadTexture("game_res/desk/angang.png",0)
Image_tag:setTouchEnabled(true);
Image_tag:setLayoutComponentEnabled(true)
Image_tag:setName("Image_tag")
Image_tag:setTag(112)
Image_tag:setCascadeColorEnabled(true)
Image_tag:setCascadeOpacityEnabled(true)
Image_tag:setPosition(0.0020, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tag)
layout:setSize({width = 125.0000, height = 121.0000})
layout:setLeftMargin(-62.4980)
layout:setRightMargin(-62.5020)
layout:setTopMargin(-60.5000)
layout:setBottomMargin(-60.5000)
Node:addChild(Image_tag)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game_res/desk/tongyongkuang.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 10, y = 10, width = 4, height = 2})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(113)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.0000, 0.5000)
Image_1:setPosition(60.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 245.0000, height = 100.0000})
layout:setLeftMargin(60.0000)
layout:setRightMargin(-305.0000)
layout:setTopMargin(-50.0000)
layout:setBottomMargin(-50.0000)
Node:addChild(Image_1)

--Create FileNode_1
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(114)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(40.7739, 46.2686)
FileNode_1:setScaleX(0.7000)
FileNode_1:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentX(0.1664)
layout:setPositionPercentY(0.4627)
layout:setLeftMargin(40.7739)
layout:setRightMargin(204.2261)
layout:setTopMargin(53.7314)
layout:setBottomMargin(46.2686)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_1:runAction(innerProject.animation)
Image_1:addChild(FileNode_1)

--Create FileNode_2
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_2 = innerProject.root
FileNode_2.animation = innerProject.animation
FileNode_2:setName("FileNode_2")
FileNode_2:setTag(121)
FileNode_2:setCascadeColorEnabled(true)
FileNode_2:setCascadeOpacityEnabled(true)
FileNode_2:setPosition(95.4144, 45.3862)
FileNode_2:setScaleX(0.7000)
FileNode_2:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_2)
layout:setPositionPercentX(0.3894)
layout:setPositionPercentY(0.4539)
layout:setLeftMargin(95.4144)
layout:setRightMargin(149.5856)
layout:setTopMargin(54.6138)
layout:setBottomMargin(45.3862)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_2:runAction(innerProject.animation)
Image_1:addChild(FileNode_2)

--Create FileNode_3
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_3 = innerProject.root
FileNode_3.animation = innerProject.animation
FileNode_3:setName("FileNode_3")
FileNode_3:setTag(128)
FileNode_3:setCascadeColorEnabled(true)
FileNode_3:setCascadeOpacityEnabled(true)
FileNode_3:setPosition(150.0543, 45.1289)
FileNode_3:setScaleX(0.7000)
FileNode_3:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_3)
layout:setPositionPercentX(0.6125)
layout:setPositionPercentY(0.4513)
layout:setLeftMargin(150.0543)
layout:setRightMargin(94.9457)
layout:setTopMargin(54.8711)
layout:setBottomMargin(45.1289)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_3:runAction(innerProject.animation)
Image_1:addChild(FileNode_3)

--Create FileNode_4
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_4 = innerProject.root
FileNode_4.animation = innerProject.animation
FileNode_4:setName("FileNode_4")
FileNode_4:setTag(475)
FileNode_4:setCascadeColorEnabled(true)
FileNode_4:setCascadeOpacityEnabled(true)
FileNode_4:setPosition(204.9229, 45.1057)
FileNode_4:setScaleX(0.7000)
FileNode_4:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_4)
layout:setPositionPercentX(0.8364)
layout:setPositionPercentY(0.4511)
layout:setLeftMargin(204.9229)
layout:setRightMargin(40.0771)
layout:setTopMargin(54.8943)
layout:setBottomMargin(45.1057)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_4:runAction(innerProject.animation)
Image_1:addChild(FileNode_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(0.5000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

