--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Button_open
local Button_open = ccui.Button:create()
Button_open:ignoreContentAdaptWithSize(false)
Button_open:loadTextureNormal("game_res/desk/shoufang1.png",0)
Button_open:setTitleFontSize(14)
Button_open:setTitleColor({r = 65, g = 65, b = 70})
Button_open:setScale9Enabled(true)
Button_open:setCapInsets({x = 15, y = 11, width = 50, height = 58})
Button_open:setLayoutComponentEnabled(true)
Button_open:setName("Button_open")
Button_open:setTag(37)
Button_open:setCascadeColorEnabled(true)
Button_open:setCascadeOpacityEnabled(true)
Button_open:setVisible(false)
Button_open:setPosition(-45.0000, -45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_open)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(-85.0000)
layout:setRightMargin(5.0000)
layout:setTopMargin(5.0000)
layout:setBottomMargin(-85.0000)
Node:addChild(Button_open)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/desk/shoufangdi.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(92)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(40.0349, -265.9876)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5004)
layout:setPositionPercentY(-3.3248)
layout:setPercentWidth(1.1500)
layout:setPercentHeight(8.7500)
layout:setSize({width = 92.0000, height = 700.0000})
layout:setLeftMargin(-5.9651)
layout:setRightMargin(-6.0349)
layout:setTopMargin(-4.0124)
layout:setBottomMargin(-615.9876)
Button_open:addChild(Image_bg)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("game_res/desk/fanhui.png",0)
Button_back:setTitleFontSize(14)
Button_back:setTitleColor({r = 65, g = 65, b = 70})
Button_back:setScale9Enabled(true)
Button_back:setCapInsets({x = 15, y = 11, width = 50, height = 76})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(39)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(40.0000, -60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.7500)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.2250)
layout:setSize({width = 80.0000, height = 98.0000})
layout:setTopMargin(91.0000)
layout:setBottomMargin(-109.0000)
Button_open:addChild(Button_back)

--Create Button_music
local Button_music = ccui.Button:create()
Button_music:ignoreContentAdaptWithSize(false)
Button_music:loadTextureNormal("game_res/desk/yinyue1.png",0)
Button_music:loadTextureDisabled("game_res/desk/yinyue2.png",0)
Button_music:setTitleFontSize(14)
Button_music:setTitleColor({r = 65, g = 65, b = 70})
Button_music:setScale9Enabled(true)
Button_music:setCapInsets({x = 15, y = 11, width = 50, height = 76})
Button_music:setLayoutComponentEnabled(true)
Button_music:setName("Button_music")
Button_music:setTag(40)
Button_music:setCascadeColorEnabled(true)
Button_music:setCascadeOpacityEnabled(true)
Button_music:setPosition(40.0000, -170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_music)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-2.1250)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.2250)
layout:setSize({width = 80.0000, height = 98.0000})
layout:setTopMargin(201.0000)
layout:setBottomMargin(-219.0000)
Button_open:addChild(Button_music)

--Create Button_sound
local Button_sound = ccui.Button:create()
Button_sound:ignoreContentAdaptWithSize(false)
Button_sound:loadTextureNormal("game_res/desk/yinxiao1.png",0)
Button_sound:loadTextureDisabled("game_res/desk/yinxiao2.png",0)
Button_sound:setTitleFontSize(14)
Button_sound:setTitleColor({r = 65, g = 65, b = 70})
Button_sound:setScale9Enabled(true)
Button_sound:setCapInsets({x = 15, y = 11, width = 50, height = 75})
Button_sound:setLayoutComponentEnabled(true)
Button_sound:setName("Button_sound")
Button_sound:setTag(41)
Button_sound:setCascadeColorEnabled(true)
Button_sound:setCascadeOpacityEnabled(true)
Button_sound:setPosition(40.0000, -280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_sound)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-3.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.2125)
layout:setSize({width = 80.0000, height = 97.0000})
layout:setTopMargin(311.5000)
layout:setBottomMargin(-328.5000)
Button_open:addChild(Button_sound)

--Create Button_fanxing
local Button_fanxing = ccui.Button:create()
Button_fanxing:ignoreContentAdaptWithSize(false)
Button_fanxing:loadTextureNormal("game_res/desk/fanxing.png",0)
Button_fanxing:setTitleFontSize(14)
Button_fanxing:setTitleColor({r = 65, g = 65, b = 70})
Button_fanxing:setScale9Enabled(true)
Button_fanxing:setCapInsets({x = 15, y = 11, width = 50, height = 76})
Button_fanxing:setLayoutComponentEnabled(true)
Button_fanxing:setName("Button_fanxing")
Button_fanxing:setTag(42)
Button_fanxing:setCascadeColorEnabled(true)
Button_fanxing:setCascadeOpacityEnabled(true)
Button_fanxing:setPosition(40.0000, -390.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_fanxing)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-4.8750)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.2250)
layout:setSize({width = 80.0000, height = 98.0000})
layout:setTopMargin(421.0000)
layout:setBottomMargin(-439.0000)
Button_open:addChild(Button_fanxing)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("game_res/desk/shoufang2.png",0)
Button_close:setTitleFontSize(14)
Button_close:setTitleColor({r = 65, g = 65, b = 70})
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 15, y = 11, width = 50, height = 58})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(38)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setPosition(-45.0000, -45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(-85.0000)
layout:setRightMargin(5.0000)
layout:setTopMargin(5.0000)
layout:setBottomMargin(-85.0000)
Node:addChild(Button_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

