--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/desk/majiangzhuo.jpg",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(15)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Image_bg)

--Create Panel_center
local Panel_center = ccui.Layout:create()
Panel_center:ignoreContentAdaptWithSize(false)
Panel_center:setClippingEnabled(false)
Panel_center:setBackGroundColorOpacity(0)
Panel_center:setTouchEnabled(true);
Panel_center:setLayoutComponentEnabled(true)
Panel_center:setName("Panel_center")
Panel_center:setTag(18)
Panel_center:setCascadeColorEnabled(true)
Panel_center:setCascadeOpacityEnabled(true)
Panel_center:setPosition(543.8937, 307.9332)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_center)
layout:setPositionPercentX(0.4249)
layout:setPositionPercentY(0.4277)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.2778)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(543.8937)
layout:setRightMargin(536.1063)
layout:setTopMargin(212.0668)
layout:setBottomMargin(307.9332)
Image_bg:addChild(Panel_center)

--Create Image_zhuang_up
local Image_zhuang_up = ccui.ImageView:create()
Image_zhuang_up:ignoreContentAdaptWithSize(false)
Image_zhuang_up:loadTexture("game_res/desk/jiantou2.png",0)
Image_zhuang_up:setLayoutComponentEnabled(true)
Image_zhuang_up:setName("Image_zhuang_up")
Image_zhuang_up:setTag(17)
Image_zhuang_up:setCascadeColorEnabled(true)
Image_zhuang_up:setCascadeOpacityEnabled(true)
Image_zhuang_up:setPosition(98.5000, 166.5262)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_zhuang_up)
layout:setPositionPercentX(0.4925)
layout:setPositionPercentY(0.8326)
layout:setPercentWidth(0.0950)
layout:setPercentHeight(0.0400)
layout:setSize({width = 19.0000, height = 8.0000})
layout:setLeftMargin(89.0000)
layout:setRightMargin(92.0000)
layout:setTopMargin(29.4738)
layout:setBottomMargin(162.5262)
Panel_center:addChild(Image_zhuang_up)

--Create Image_zhuang_up_light
local Image_zhuang_up_light = ccui.ImageView:create()
Image_zhuang_up_light:ignoreContentAdaptWithSize(false)
Image_zhuang_up_light:loadTexture("game_res/desk/gaoliang2.png",0)
Image_zhuang_up_light:setLayoutComponentEnabled(true)
Image_zhuang_up_light:setName("Image_zhuang_up_light")
Image_zhuang_up_light:setTag(88)
Image_zhuang_up_light:setCascadeColorEnabled(true)
Image_zhuang_up_light:setCascadeOpacityEnabled(true)
Image_zhuang_up_light:setPosition(98.6600, 146.7705)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_zhuang_up_light)
layout:setPositionPercentX(0.4933)
layout:setPositionPercentY(0.7339)
layout:setPercentWidth(0.4450)
layout:setPercentHeight(0.0800)
layout:setSize({width = 89.0000, height = 16.0000})
layout:setLeftMargin(54.1600)
layout:setRightMargin(56.8400)
layout:setTopMargin(45.2295)
layout:setBottomMargin(138.7705)
Panel_center:addChild(Image_zhuang_up_light)

--Create Image_zhuang_down
local Image_zhuang_down = ccui.ImageView:create()
Image_zhuang_down:ignoreContentAdaptWithSize(false)
Image_zhuang_down:loadTexture("game_res/desk/jiantou1.png",0)
Image_zhuang_down:setLayoutComponentEnabled(true)
Image_zhuang_down:setName("Image_zhuang_down")
Image_zhuang_down:setTag(19)
Image_zhuang_down:setCascadeColorEnabled(true)
Image_zhuang_down:setCascadeOpacityEnabled(true)
Image_zhuang_down:setPosition(98.5000, 44.3432)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_zhuang_down)
layout:setPositionPercentX(0.4925)
layout:setPositionPercentY(0.2217)
layout:setPercentWidth(0.1150)
layout:setPercentHeight(0.0550)
layout:setSize({width = 23.0000, height = 11.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(90.0000)
layout:setTopMargin(150.1568)
layout:setBottomMargin(38.8432)
Panel_center:addChild(Image_zhuang_down)

--Create Image_zhuang_down_light
local Image_zhuang_down_light = ccui.ImageView:create()
Image_zhuang_down_light:ignoreContentAdaptWithSize(false)
Image_zhuang_down_light:loadTexture("game_res/desk/gaoliang1.png",0)
Image_zhuang_down_light:setLayoutComponentEnabled(true)
Image_zhuang_down_light:setName("Image_zhuang_down_light")
Image_zhuang_down_light:setTag(89)
Image_zhuang_down_light:setCascadeColorEnabled(true)
Image_zhuang_down_light:setCascadeOpacityEnabled(true)
Image_zhuang_down_light:setPosition(98.2298, 72.1300)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_zhuang_down_light)
layout:setPositionPercentX(0.4911)
layout:setPositionPercentY(0.3606)
layout:setPercentWidth(0.4950)
layout:setPercentHeight(0.1000)
layout:setSize({width = 99.0000, height = 20.0000})
layout:setLeftMargin(48.7298)
layout:setRightMargin(52.2702)
layout:setTopMargin(117.8700)
layout:setBottomMargin(62.1300)
Panel_center:addChild(Image_zhuang_down_light)

--Create Text_countdownTime
local Text_countdownTime = ccui.Text:create()
Text_countdownTime:ignoreContentAdaptWithSize(true)
Text_countdownTime:setTextAreaSize({width = 0, height = 0})
Text_countdownTime:setFontSize(20)
Text_countdownTime:setString([[10S]])
Text_countdownTime:setLayoutComponentEnabled(true)
Text_countdownTime:setName("Text_countdownTime")
Text_countdownTime:setTag(36)
Text_countdownTime:setCascadeColorEnabled(true)
Text_countdownTime:setCascadeOpacityEnabled(true)
Text_countdownTime:setPosition(98.8339, 129.1007)
Text_countdownTime:setTextColor({r = 233, g = 249, b = 128})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_countdownTime)
layout:setPositionPercentX(0.4942)
layout:setPositionPercentY(0.6455)
layout:setPercentWidth(0.1500)
layout:setPercentHeight(0.1000)
layout:setSize({width = 30.0000, height = 20.0000})
layout:setLeftMargin(83.8339)
layout:setRightMargin(86.1661)
layout:setTopMargin(60.8993)
layout:setBottomMargin(119.1007)
Panel_center:addChild(Text_countdownTime)

--Create Image_tubiao
local Image_tubiao = ccui.ImageView:create()
Image_tubiao:ignoreContentAdaptWithSize(false)
Image_tubiao:loadTexture("game_res/desk/xiaotubiao.png",0)
Image_tubiao:setLayoutComponentEnabled(true)
Image_tubiao:setName("Image_tubiao")
Image_tubiao:setTag(20)
Image_tubiao:setCascadeColorEnabled(true)
Image_tubiao:setCascadeOpacityEnabled(true)
Image_tubiao:setPosition(81.5927, 97.2099)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tubiao)
layout:setPositionPercentX(0.4080)
layout:setPositionPercentY(0.4860)
layout:setPercentWidth(0.1000)
layout:setPercentHeight(0.1200)
layout:setSize({width = 20.0000, height = 24.0000})
layout:setLeftMargin(71.5927)
layout:setRightMargin(108.4073)
layout:setTopMargin(90.7901)
layout:setBottomMargin(85.2099)
Panel_center:addChild(Image_tubiao)

--Create Text_restCardCount
local Text_restCardCount = ccui.Text:create()
Text_restCardCount:ignoreContentAdaptWithSize(true)
Text_restCardCount:setTextAreaSize({width = 0, height = 0})
Text_restCardCount:setFontSize(16)
Text_restCardCount:setString([[x0]])
Text_restCardCount:setLayoutComponentEnabled(true)
Text_restCardCount:setName("Text_restCardCount")
Text_restCardCount:setTag(37)
Text_restCardCount:setCascadeColorEnabled(true)
Text_restCardCount:setCascadeOpacityEnabled(true)
Text_restCardCount:setAnchorPoint(0.0000, 0.5000)
Text_restCardCount:setPosition(96.9222, 97.3332)
Text_restCardCount:setTextColor({r = 233, g = 249, b = 128})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_restCardCount)
layout:setPositionPercentX(0.4846)
layout:setPositionPercentY(0.4867)
layout:setPercentWidth(0.0800)
layout:setPercentHeight(0.0800)
layout:setSize({width = 16.0000, height = 16.0000})
layout:setLeftMargin(96.9222)
layout:setRightMargin(87.0778)
layout:setTopMargin(94.6668)
layout:setBottomMargin(89.3332)
Panel_center:addChild(Text_restCardCount)

--Create Image_type
local Image_type = ccui.ImageView:create()
Image_type:ignoreContentAdaptWithSize(false)
Image_type:loadTexture("game_res/desk/xiaoquechang.png",0)
Image_type:setLayoutComponentEnabled(true)
Image_type:setName("Image_type")
Image_type:setTag(21)
Image_type:setCascadeColorEnabled(true)
Image_type:setCascadeOpacityEnabled(true)
Image_type:setPosition(-25.6586, 106.2820)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_type)
layout:setPositionPercentX(-0.1283)
layout:setPositionPercentY(0.5314)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.0800)
layout:setSize({width = 70.0000, height = 16.0000})
layout:setLeftMargin(-60.6586)
layout:setRightMargin(190.6586)
layout:setTopMargin(85.7180)
layout:setBottomMargin(98.2820)
Panel_center:addChild(Image_type)

--Create Image_bottom_pour
local Image_bottom_pour = ccui.ImageView:create()
Image_bottom_pour:ignoreContentAdaptWithSize(false)
Image_bottom_pour:loadTexture("game_res/desk/dizhu.png",0)
Image_bottom_pour:setLayoutComponentEnabled(true)
Image_bottom_pour:setName("Image_bottom_pour")
Image_bottom_pour:setTag(22)
Image_bottom_pour:setCascadeColorEnabled(true)
Image_bottom_pour:setCascadeOpacityEnabled(true)
Image_bottom_pour:setPosition(208.8090, 106.2800)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bottom_pour)
layout:setPositionPercentX(1.0440)
layout:setPositionPercentY(0.5314)
layout:setPercentWidth(0.2400)
layout:setPercentHeight(0.0800)
layout:setSize({width = 48.0000, height = 16.0000})
layout:setLeftMargin(184.8090)
layout:setRightMargin(-32.8090)
layout:setTopMargin(85.7200)
layout:setBottomMargin(98.2800)
Panel_center:addChild(Image_bottom_pour)

--Create AtlasLabel_pour
local AtlasLabel_pour = ccui.TextAtlas:create([[0]],
													"game_res/desk/dizhushuzi.png",
													13,
													21,
													"/")
AtlasLabel_pour:setLayoutComponentEnabled(true)
AtlasLabel_pour:setName("AtlasLabel_pour")
AtlasLabel_pour:setTag(23)
AtlasLabel_pour:setCascadeColorEnabled(true)
AtlasLabel_pour:setCascadeOpacityEnabled(true)
AtlasLabel_pour:setAnchorPoint(0.0000, 0.5000)
AtlasLabel_pour:setPosition(237.4992, 106.0128)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_pour)
layout:setPositionPercentX(1.1875)
layout:setPositionPercentY(0.5301)
layout:setPercentWidth(0.0650)
layout:setPercentHeight(0.1050)
layout:setSize({width = 13.0000, height = 21.0000})
layout:setLeftMargin(237.4992)
layout:setRightMargin(-50.4992)
layout:setTopMargin(83.4872)
layout:setBottomMargin(95.5128)
Panel_center:addChild(AtlasLabel_pour)

--Create FileNode_task
innerCSD = require("TmjTaskNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_task = innerProject.root
FileNode_task.animation = innerProject.animation
FileNode_task:setName("FileNode_task")
FileNode_task:setTag(24)
FileNode_task:setCascadeColorEnabled(true)
FileNode_task:setCascadeOpacityEnabled(true)
FileNode_task:setPosition(50.7132, 656.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_task)
layout:setPositionPercentX(0.0396)
layout:setPositionPercentY(0.9111)
layout:setLeftMargin(50.7132)
layout:setRightMargin(1229.2870)
layout:setTopMargin(64.0000)
layout:setBottomMargin(656.0000)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_task:runAction(innerProject.animation)
Image_bg:addChild(FileNode_task)

--Create Node_operationPos
local Node_operationPos=cc.Node:create()
Node_operationPos:setName("Node_operationPos")
Node_operationPos:setTag(426)
Node_operationPos:setCascadeColorEnabled(true)
Node_operationPos:setCascadeOpacityEnabled(true)
Node_operationPos:setPosition(1224.2500, 143.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_operationPos)
layout:setPositionPercentX(0.9564)
layout:setPositionPercentY(0.1996)
layout:setLeftMargin(1224.2500)
layout:setRightMargin(55.7500)
layout:setTopMargin(576.3000)
layout:setBottomMargin(143.7000)
Image_bg:addChild(Node_operationPos)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

