--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game_res/desk/tongyongkuang.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 10, y = 10, width = 4, height = 2})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(104)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.5000, 0.0000)
Image_1:setPosition(0.0000, -50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 82.0000, height = 150.0000})
layout:setLeftMargin(-41.0000)
layout:setRightMargin(-41.0000)
layout:setTopMargin(-100.0000)
layout:setBottomMargin(-50.0000)
Node:addChild(Image_1)

--Create FileNode_1
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(105)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(40.7741, 94.2695)
FileNode_1:setScaleX(0.7000)
FileNode_1:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentX(0.4972)
layout:setPositionPercentY(0.6285)
layout:setLeftMargin(40.7741)
layout:setRightMargin(41.2259)
layout:setTopMargin(55.7305)
layout:setBottomMargin(94.2695)
innerProject.animation:setTimeSpeed(0.5000)
FileNode_1:runAction(innerProject.animation)
Image_1:addChild(FileNode_1)

--Create Text_restCard
local Text_restCard = ccui.Text:create()
Text_restCard:ignoreContentAdaptWithSize(true)
Text_restCard:setTextAreaSize({width = 0, height = 0})
Text_restCard:setFontSize(14)
Text_restCard:setString([[剩余0张]])
Text_restCard:setLayoutComponentEnabled(true)
Text_restCard:setName("Text_restCard")
Text_restCard:setTag(126)
Text_restCard:setCascadeColorEnabled(true)
Text_restCard:setCascadeOpacityEnabled(true)
Text_restCard:setPosition(41.0000, 39.5266)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_restCard)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2635)
layout:setPercentWidth(0.5976)
layout:setPercentHeight(0.0933)
layout:setSize({width = 49.0000, height = 14.0000})
layout:setLeftMargin(16.5000)
layout:setRightMargin(16.5000)
layout:setTopMargin(103.4734)
layout:setBottomMargin(32.5266)
Image_1:addChild(Text_restCard)

--Create Text_fan
local Text_fan = ccui.Text:create()
Text_fan:ignoreContentAdaptWithSize(true)
Text_fan:setTextAreaSize({width = 0, height = 0})
Text_fan:setFontSize(14)
Text_fan:setString([[0番]])
Text_fan:setLayoutComponentEnabled(true)
Text_fan:setName("Text_fan")
Text_fan:setTag(127)
Text_fan:setCascadeColorEnabled(true)
Text_fan:setCascadeOpacityEnabled(true)
Text_fan:setPosition(41.0000, 17.5523)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_fan)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1170)
layout:setPercentWidth(0.2561)
layout:setPercentHeight(0.0933)
layout:setSize({width = 21.0000, height = 14.0000})
layout:setLeftMargin(30.5000)
layout:setRightMargin(30.5000)
layout:setTopMargin(125.4477)
layout:setBottomMargin(10.5523)
Image_1:addChild(Text_fan)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

