--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Button_ting_cancel
local Button_ting_cancel = ccui.Button:create()
Button_ting_cancel:ignoreContentAdaptWithSize(false)
Button_ting_cancel:loadTextureNormal("game_res/desk/anquxiao.png",0)
Button_ting_cancel:setTitleFontSize(14)
Button_ting_cancel:setTitleColor({r = 65, g = 65, b = 70})
Button_ting_cancel:setScale9Enabled(true)
Button_ting_cancel:setCapInsets({x = 15, y = 11, width = 95, height = 99})
Button_ting_cancel:setLayoutComponentEnabled(true)
Button_ting_cancel:setName("Button_ting_cancel")
Button_ting_cancel:setTag(957)
Button_ting_cancel:setCascadeColorEnabled(true)
Button_ting_cancel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_ting_cancel)
layout:setSize({width = 125.0000, height = 121.0000})
layout:setLeftMargin(-62.5000)
layout:setRightMargin(-62.5000)
layout:setTopMargin(-60.5000)
layout:setBottomMargin(-60.5000)
Node:addChild(Button_ting_cancel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

