--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(23)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create bg_view
local bg_view = ccui.Layout:create()
bg_view:ignoreContentAdaptWithSize(false)
bg_view:setClippingEnabled(false)
bg_view:setBackGroundColorType(1)
bg_view:setBackGroundColor({r = 0, g = 0, b = 0})
bg_view:setBackGroundColorOpacity(127)
bg_view:setTouchEnabled(true);
bg_view:setLayoutComponentEnabled(true)
bg_view:setName("bg_view")
bg_view:setTag(21)
bg_view:setCascadeColorEnabled(true)
bg_view:setCascadeOpacityEnabled(true)
bg_view:setAnchorPoint(0.5000, 0.5000)
bg_view:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Panel_1:addChild(bg_view)

--Create tip_parent_view
local tip_parent_view = ccui.Layout:create()
tip_parent_view:ignoreContentAdaptWithSize(false)
tip_parent_view:setClippingEnabled(false)
tip_parent_view:setBackGroundColorOpacity(102)
tip_parent_view:setTouchEnabled(true);
tip_parent_view:setLayoutComponentEnabled(true)
tip_parent_view:setName("tip_parent_view")
tip_parent_view:setTag(24)
tip_parent_view:setCascadeColorEnabled(true)
tip_parent_view:setCascadeOpacityEnabled(true)
tip_parent_view:setAnchorPoint(0.5000, 0.5000)
tip_parent_view:setPosition(640.0000, 324.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_parent_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4506)
layout:setPercentWidth(0.4060)
layout:setPercentHeight(0.1747)
layout:setSize({width = 519.6307, height = 125.7600})
layout:setLeftMargin(380.1847)
layout:setRightMargin(380.1847)
layout:setTopMargin(332.7200)
layout:setBottomMargin(261.5200)
bg_view:addChild(tip_parent_view)

--Create tipText
local tipText = ccui.Text:create()
tipText:ignoreContentAdaptWithSize(true)
tipText:setTextAreaSize({width = 0, height = 0})
tipText:setFontSize(30)
tipText:setString([[请稍后。。。]])
tipText:setLayoutComponentEnabled(true)
tipText:setName("tipText")
tipText:setTag(25)
tipText:setCascadeColorEnabled(true)
tipText:setCascadeOpacityEnabled(true)
tipText:setAnchorPoint(0.0000, 0.5000)
tipText:setPosition(186.6141, 62.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(tipText)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3591)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3464)
layout:setPercentHeight(0.2385)
layout:setSize({width = 180.0000, height = 30.0000})
layout:setLeftMargin(186.6141)
layout:setRightMargin(153.0166)
layout:setTopMargin(47.8800)
layout:setBottomMargin(47.8800)
tip_parent_view:addChild(tipText)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("frame_res/loading.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(26)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(81.7501, 62.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1573)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1886)
layout:setPercentHeight(0.7793)
layout:setSize({width = 98.0000, height = 98.0000})
layout:setLeftMargin(32.7501)
layout:setRightMargin(388.8806)
layout:setTopMargin(13.8800)
layout:setBottomMargin(13.8800)
tip_parent_view:addChild(Image_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

