--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg_panel
local bg_panel = ccui.Layout:create()
bg_panel:ignoreContentAdaptWithSize(false)
bg_panel:setClippingEnabled(false)
bg_panel:setBackGroundColorType(1)
bg_panel:setBackGroundColor({r = 0, g = 0, b = 0})
bg_panel:setBackGroundColorOpacity(102)
bg_panel:setTouchEnabled(true);
bg_panel:setLayoutComponentEnabled(true)
bg_panel:setName("bg_panel")
bg_panel:setTag(16)
bg_panel:setCascadeColorEnabled(true)
bg_panel:setCascadeOpacityEnabled(true)
bg_panel:setAnchorPoint(0.5000, 0.5000)
bg_panel:setPosition(641.0240, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5008)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(1.0240)
layout:setRightMargin(-1.0240)
Layer:addChild(bg_panel)

--Create alert_view
local alert_view = ccui.Layout:create()
alert_view:ignoreContentAdaptWithSize(false)
alert_view:setBackGroundImage("frame_res/bombbox/bb_ty_tc1.png",0)
alert_view:setClippingEnabled(false)
alert_view:setBackGroundImageCapInsets({x = 183, y = 70, width = 434, height = 321})
alert_view:setBackGroundImageScale9Enabled(true)
alert_view:setTouchEnabled(true);
alert_view:setLayoutComponentEnabled(true)
alert_view:setName("alert_view")
alert_view:setTag(17)
alert_view:setCascadeColorEnabled(true)
alert_view:setCascadeOpacityEnabled(true)
alert_view:setAnchorPoint(0.5000, 0.5000)
alert_view:setPosition(640.0000, 386.4960)
layout = ccui.LayoutComponent:bindLayoutComponent(alert_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5368)
layout:setPercentWidth(0.5828)
layout:setPercentHeight(0.5556)
layout:setSize({width = 746.0000, height = 400.0000})
layout:setLeftMargin(267.0000)
layout:setRightMargin(267.0000)
layout:setTopMargin(133.5040)
layout:setBottomMargin(186.4960)
Layer:addChild(alert_view)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontSize(40)
Text_1:setString([[温馨提示]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(34)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(373.0000, 360.2600)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9007)
layout:setPercentWidth(0.2145)
layout:setPercentHeight(0.1000)
layout:setSize({width = 160.0000, height = 40.0000})
layout:setLeftMargin(293.0000)
layout:setRightMargin(293.0000)
layout:setTopMargin(19.7400)
layout:setBottomMargin(340.2600)
alert_view:addChild(Text_1)

--Create contentTextNode
local contentTextNode = ccui.Text:create()
contentTextNode:ignoreContentAdaptWithSize(false)
contentTextNode:setFontSize(30)
contentTextNode:setString([[提示框的文字 提示框的文字 提示框的文字 提示框的文字 提示框的文字]])
contentTextNode:setTextHorizontalAlignment(1)
contentTextNode:setTextVerticalAlignment(1)
contentTextNode:setLayoutComponentEnabled(true)
contentTextNode:setName("contentTextNode")
contentTextNode:setTag(18)
contentTextNode:setCascadeColorEnabled(true)
contentTextNode:setCascadeOpacityEnabled(true)
contentTextNode:setPosition(370.1652, 220.9569)
layout = ccui.LayoutComponent:bindLayoutComponent(contentTextNode)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4962)
layout:setPositionPercentY(0.5524)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(0.8000)
layout:setPercentHeight(0.4500)
layout:setSize({width = 596.8000, height = 180.0000})
layout:setLeftMargin(71.7652)
layout:setRightMargin(77.4348)
layout:setTopMargin(89.0431)
layout:setBottomMargin(130.9569)
alert_view:addChild(contentTextNode)

--Create confirmBtn
local confirmBtn = ccui.Button:create()
confirmBtn:ignoreContentAdaptWithSize(false)
confirmBtn:loadTextureNormal("frame_res/bombbox/bb_grxx_queren.png",0)
confirmBtn:loadTexturePressed("frame_res/bombbox/bb_grxx_queren1.png",0)
confirmBtn:loadTextureDisabled("frame_res/bombbox/bb_grxx_queren1.png",0)
confirmBtn:setTitleFontSize(30)
confirmBtn:setTitleColor({r = 65, g = 65, b = 70})
confirmBtn:setScale9Enabled(true)
confirmBtn:setCapInsets({x = 15, y = 11, width = 257, height = 78})
confirmBtn:setLayoutComponentEnabled(true)
confirmBtn:setName("confirmBtn")
confirmBtn:setTag(19)
confirmBtn:setCascadeColorEnabled(true)
confirmBtn:setCascadeOpacityEnabled(true)
confirmBtn:setPosition(557.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(confirmBtn)
layout:setPositionPercentX(0.7466)
layout:setPositionPercentY(0.1575)
layout:setPercentWidth(0.3847)
layout:setPercentHeight(0.2500)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(413.5000)
layout:setRightMargin(45.5000)
layout:setTopMargin(287.0000)
layout:setBottomMargin(13.0000)
alert_view:addChild(confirmBtn)

--Create cancelBtn
local cancelBtn = ccui.Button:create()
cancelBtn:ignoreContentAdaptWithSize(false)
cancelBtn:loadTextureNormal("frame_res/bombbox/bb_grxx_quxiao.png",0)
cancelBtn:loadTexturePressed("frame_res/bombbox/bb_grxx_quxiao1.png",0)
cancelBtn:loadTextureDisabled("frame_res/bombbox/bb_grxx_quxiao1.png",0)
cancelBtn:setTitleFontSize(30)
cancelBtn:setTitleColor({r = 65, g = 65, b = 70})
cancelBtn:setScale9Enabled(true)
cancelBtn:setCapInsets({x = 15, y = 11, width = 257, height = 78})
cancelBtn:setLayoutComponentEnabled(true)
cancelBtn:setName("cancelBtn")
cancelBtn:setTag(21)
cancelBtn:setCascadeColorEnabled(true)
cancelBtn:setCascadeOpacityEnabled(true)
cancelBtn:setAnchorPoint(0.4816, 0.5581)
cancelBtn:setPosition(183.8323, 71.7692)
layout = ccui.LayoutComponent:bindLayoutComponent(cancelBtn)
layout:setPositionPercentX(0.2464)
layout:setPositionPercentY(0.1794)
layout:setPercentWidth(0.3847)
layout:setPercentHeight(0.2500)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(45.6163)
layout:setRightMargin(413.3837)
layout:setTopMargin(284.0382)
layout:setBottomMargin(15.9618)
alert_view:addChild(cancelBtn)

--Create close_btn
local close_btn = ccui.Button:create()
close_btn:ignoreContentAdaptWithSize(false)
close_btn:loadTextureNormal("frame_res/bombbox/bb_ty_gb.png",0)
close_btn:loadTexturePressed("frame_res/bombbox/bb_ty_gb1.png",0)
close_btn:loadTextureDisabled("frame_res/bombbox/bb_ty_gb1.png",0)
close_btn:setTitleFontSize(14)
close_btn:setTitleColor({r = 65, g = 65, b = 70})
close_btn:setScale9Enabled(true)
close_btn:setCapInsets({x = 15, y = 11, width = 37, height = 46})
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setTag(19)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setAnchorPoint(0.5347, 0.4410)
close_btn:setPosition(721.1018, 369.8236)
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentX(0.9666)
layout:setPositionPercentY(0.9246)
layout:setPercentWidth(0.0898)
layout:setPercentHeight(0.1700)
layout:setSize({width = 67.0000, height = 68.0000})
layout:setLeftMargin(685.2769)
layout:setRightMargin(-6.2769)
layout:setTopMargin(-7.8356)
layout:setBottomMargin(339.8356)
alert_view:addChild(close_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

