--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create base_layout
local base_layout = ccui.Layout:create()
base_layout:ignoreContentAdaptWithSize(false)
base_layout:setBackGroundImage("game_res/wz_yxgz.png",0)
base_layout:setClippingEnabled(true)
base_layout:setBackGroundColorType(1)
base_layout:setBackGroundColor({r = 26, g = 26, b = 26})
base_layout:setBackGroundColorOpacity(102)
base_layout:setTouchEnabled(true);
base_layout:setLayoutComponentEnabled(true)
base_layout:setName("base_layout")
base_layout:setTag(92)
base_layout:setCascadeColorEnabled(true)
base_layout:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(base_layout)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(base_layout)

--Create pageView
local pageView = ccui.ListView:create()
pageView:setDirection(1)
pageView:setGravity(2)
pageView:ignoreContentAdaptWithSize(false)
pageView:setClippingEnabled(true)
pageView:setBackGroundColorOpacity(102)
pageView:setLayoutComponentEnabled(true)
pageView:setName("pageView")
pageView:setTag(95)
pageView:setCascadeColorEnabled(true)
pageView:setCascadeOpacityEnabled(true)
pageView:setPosition(163.6800, 112.7189)
layout = ccui.LayoutComponent:bindLayoutComponent(pageView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.1279)
layout:setPositionPercentY(0.1566)
layout:setPercentWidth(0.7422)
layout:setPercentHeight(0.6431)
layout:setSize({width = 950.0000, height = 463.0000})
layout:setLeftMargin(163.6800)
layout:setRightMargin(166.3201)
layout:setTopMargin(144.2811)
layout:setBottomMargin(112.7189)
base_layout:addChild(pageView)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("game_res/wz_bt_gb.png",0)
btn_close:loadTexturePressed("game_res/wz_bt_gb_2.png",0)
btn_close:loadTextureDisabled("game_res/wz_bt_gb_2.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 72, height = 82})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(97)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(1105.9570, 641.8237)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8640)
layout:setPositionPercentY(0.8914)
layout:setPercentWidth(0.0797)
layout:setPercentHeight(0.1444)
layout:setSize({width = 102.0000, height = 104.0000})
layout:setLeftMargin(1054.9570)
layout:setRightMargin(123.0435)
layout:setTopMargin(26.1763)
layout:setBottomMargin(589.8237)
base_layout:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

