--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/secondView/sh_px.png",0)
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(12)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(210.0000, 318.2592)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.1641)
layout:setPositionPercentY(0.4420)
layout:setPercentWidth(0.2844)
layout:setPercentHeight(0.8042)
layout:setSize({width = 364.0000, height = 579.0000})
layout:setLeftMargin(28.0000)
layout:setRightMargin(888.0000)
layout:setTopMargin(112.2408)
layout:setBottomMargin(28.7592)
Layer:addChild(Image_bg)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(165)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(182.0000, 35.7387)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0617)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(510.7613)
layout:setBottomMargin(3.2387)
Image_bg:addChild(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(166)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(182.0000, 102.0198)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1762)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(444.4802)
layout:setBottomMargin(69.5198)
Image_bg:addChild(Image_2)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(167)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(182.0000, 165.9526)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2866)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(380.5474)
layout:setBottomMargin(133.4526)
Image_bg:addChild(Image_3)

--Create Image_4
local Image_4 = ccui.ImageView:create()
Image_4:ignoreContentAdaptWithSize(false)
Image_4:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setTag(168)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setPosition(182.0000, 228.7983)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3952)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(317.7017)
layout:setBottomMargin(196.2983)
Image_bg:addChild(Image_4)

--Create Image_5
local Image_5 = ccui.ImageView:create()
Image_5:ignoreContentAdaptWithSize(false)
Image_5:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_5:setLayoutComponentEnabled(true)
Image_5:setName("Image_5")
Image_5:setTag(169)
Image_5:setCascadeColorEnabled(true)
Image_5:setCascadeOpacityEnabled(true)
Image_5:setPosition(182.0000, 292.7317)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_5)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5056)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(253.7683)
layout:setBottomMargin(260.2317)
Image_bg:addChild(Image_5)

--Create Image_6
local Image_6 = ccui.ImageView:create()
Image_6:ignoreContentAdaptWithSize(false)
Image_6:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_6:setLayoutComponentEnabled(true)
Image_6:setName("Image_6")
Image_6:setTag(170)
Image_6:setCascadeColorEnabled(true)
Image_6:setCascadeOpacityEnabled(true)
Image_6:setPosition(182.0000, 353.7525)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_6)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6110)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(192.7475)
layout:setBottomMargin(321.2525)
Image_bg:addChild(Image_6)

--Create Image_7
local Image_7 = ccui.ImageView:create()
Image_7:ignoreContentAdaptWithSize(false)
Image_7:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_7:setLayoutComponentEnabled(true)
Image_7:setName("Image_7")
Image_7:setTag(171)
Image_7:setCascadeColorEnabled(true)
Image_7:setCascadeOpacityEnabled(true)
Image_7:setPosition(182.0000, 415.9048)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_7)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7183)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(130.5952)
layout:setBottomMargin(383.4048)
Image_bg:addChild(Image_7)

--Create Image_8
local Image_8 = ccui.ImageView:create()
Image_8:ignoreContentAdaptWithSize(false)
Image_8:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_8:setLayoutComponentEnabled(true)
Image_8:setName("Image_8")
Image_8:setTag(172)
Image_8:setCascadeColorEnabled(true)
Image_8:setCascadeOpacityEnabled(true)
Image_8:setPosition(182.0000, 477.6395)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_8)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8249)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(68.8605)
layout:setBottomMargin(445.1395)
Image_bg:addChild(Image_8)

--Create Image_9
local Image_9 = ccui.ImageView:create()
Image_9:ignoreContentAdaptWithSize(false)
Image_9:loadTexture("game_res/secondView/sh_px_xuanzhong.png",0)
Image_9:setLayoutComponentEnabled(true)
Image_9:setName("Image_9")
Image_9:setTag(173)
Image_9:setCascadeColorEnabled(true)
Image_9:setCascadeOpacityEnabled(true)
Image_9:setPosition(182.0000, 543.6396)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_9)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9389)
layout:setPercentWidth(0.9863)
layout:setPercentHeight(0.1123)
layout:setSize({width = 359.0000, height = 65.0000})
layout:setLeftMargin(2.5000)
layout:setRightMargin(2.5000)
layout:setTopMargin(2.8604)
layout:setBottomMargin(511.1396)
Image_bg:addChild(Image_9)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

