--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_chatbg
local Image_chatbg = ccui.ImageView:create()
Image_chatbg:ignoreContentAdaptWithSize(false)
Image_chatbg:loadTexture("game_res/secondView/sh_px_kuang.png",0)
Image_chatbg:setLayoutComponentEnabled(true)
Image_chatbg:setName("Image_chatbg")
Image_chatbg:setTag(8)
Image_chatbg:setCascadeColorEnabled(true)
Image_chatbg:setCascadeOpacityEnabled(true)
Image_chatbg:setPosition(331.7200, 23.3677)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_chatbg)
layout:setSize({width = 660.0000, height = 42.0000})
layout:setLeftMargin(1.7200)
layout:setRightMargin(-661.7200)
layout:setTopMargin(-44.3677)
layout:setBottomMargin(2.3677)
Node:addChild(Image_chatbg)

--Create Text_content
local Text_content = ccui.Text:create()
Text_content:ignoreContentAdaptWithSize(true)
Text_content:setTextAreaSize({width = 0, height = 0})
Text_content:setFontSize(28)
Text_content:setString([[在等什么，快下注吧]])
Text_content:setLayoutComponentEnabled(true)
Text_content:setName("Text_content")
Text_content:setTag(9)
Text_content:setCascadeColorEnabled(true)
Text_content:setCascadeOpacityEnabled(true)
Text_content:setPosition(330.0000, 21.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_content)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3818)
layout:setPercentHeight(0.6667)
layout:setSize({width = 252.0000, height = 28.0000})
layout:setLeftMargin(204.0000)
layout:setRightMargin(204.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(7.0000)
Image_chatbg:addChild(Text_content)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

