--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/secondView/sh_kjfy_kuang.png",0)
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(4)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(360.0000, 281.1600)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.2813)
layout:setPositionPercentY(0.3905)
layout:setPercentWidth(0.5359)
layout:setPercentHeight(0.6306)
layout:setSize({width = 686.0000, height = 454.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(577.0000)
layout:setTopMargin(211.8400)
layout:setBottomMargin(54.1600)
Layer:addChild(Image_bg)

--Create Panel_chat
local Panel_chat = ccui.Layout:create()
Panel_chat:ignoreContentAdaptWithSize(false)
Panel_chat:setClippingEnabled(false)
Panel_chat:setBackGroundColorOpacity(102)
Panel_chat:setTouchEnabled(true);
Panel_chat:setLayoutComponentEnabled(true)
Panel_chat:setName("Panel_chat")
Panel_chat:setTag(95)
Panel_chat:setCascadeColorEnabled(true)
Panel_chat:setCascadeOpacityEnabled(true)
Panel_chat:setAnchorPoint(0.5000, 0.5000)
Panel_chat:setPosition(341.1879, 192.1506)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_chat)
layout:setPositionPercentX(0.4974)
layout:setPositionPercentY(0.4232)
layout:setPercentWidth(0.9621)
layout:setPercentHeight(0.7709)
layout:setSize({width = 660.0000, height = 350.0000})
layout:setLeftMargin(11.1879)
layout:setRightMargin(14.8121)
layout:setTopMargin(86.8494)
layout:setBottomMargin(17.1506)
Image_bg:addChild(Panel_chat)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

