--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/mainView/sh_bj.jpg",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(28)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Image_bg)

--Create Image_ready
local Image_ready = ccui.ImageView:create()
Image_ready:ignoreContentAdaptWithSize(false)
Image_ready:loadTexture("game_res/mainView/sh_ppz.png",0)
Image_ready:setLayoutComponentEnabled(true)
Image_ready:setName("Image_ready")
Image_ready:setTag(71)
Image_ready:setCascadeColorEnabled(true)
Image_ready:setCascadeOpacityEnabled(true)
Image_ready:setPosition(640.0013, 390.0004)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_ready)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5417)
layout:setPercentWidth(0.2523)
layout:setPercentHeight(0.0847)
layout:setSize({width = 323.0000, height = 61.0000})
layout:setLeftMargin(478.5013)
layout:setRightMargin(478.4987)
layout:setTopMargin(299.4996)
layout:setBottomMargin(359.5004)
Image_bg:addChild(Image_ready)

--Create Panel_bet
local Panel_bet = ccui.Layout:create()
Panel_bet:ignoreContentAdaptWithSize(false)
Panel_bet:setClippingEnabled(false)
Panel_bet:setBackGroundColorOpacity(102)
Panel_bet:setTouchEnabled(true);
Panel_bet:setLayoutComponentEnabled(true)
Panel_bet:setName("Panel_bet")
Panel_bet:setTag(914)
Panel_bet:setCascadeColorEnabled(true)
Panel_bet:setCascadeOpacityEnabled(true)
Panel_bet:setAnchorPoint(0.5000, 0.5000)
Panel_bet:setPosition(610.6805, 418.6900)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_bet)
layout:setPositionPercentX(0.4771)
layout:setPositionPercentY(0.5815)
layout:setPercentWidth(0.3594)
layout:setPercentHeight(0.2083)
layout:setSize({width = 460.0000, height = 150.0000})
layout:setLeftMargin(380.6805)
layout:setRightMargin(439.3195)
layout:setTopMargin(226.3100)
layout:setBottomMargin(343.6900)
Image_bg:addChild(Panel_bet)

--Create FileNode_me
innerCSD = require("SHHeadNode_1")
innerProject = innerCSD.create(callBackProvider)
local FileNode_me = innerProject.root
FileNode_me.animation = innerProject.animation
FileNode_me:setName("FileNode_me")
FileNode_me:setTag(474)
FileNode_me:setCascadeColorEnabled(true)
FileNode_me:setCascadeOpacityEnabled(true)
FileNode_me:setPosition(378.3608, 206.5748)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_me)
layout:setPositionPercentX(0.2956)
layout:setPositionPercentY(0.2869)
layout:setLeftMargin(378.3608)
layout:setRightMargin(901.6392)
layout:setTopMargin(513.4252)
layout:setBottomMargin(206.5748)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_me:runAction(innerProject.animation)
Image_bg:addChild(FileNode_me)

--Create FileNode_other
innerCSD = require("SHHeadNode_2")
innerProject = innerCSD.create(callBackProvider)
local FileNode_other = innerProject.root
FileNode_other.animation = innerProject.animation
FileNode_other:setName("FileNode_other")
FileNode_other:setTag(510)
FileNode_other:setCascadeColorEnabled(true)
FileNode_other:setCascadeOpacityEnabled(true)
FileNode_other:setPosition(388.5899, 591.5573)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_other)
layout:setPositionPercentX(0.3036)
layout:setPositionPercentY(0.8216)
layout:setLeftMargin(388.5899)
layout:setRightMargin(891.4101)
layout:setTopMargin(128.4427)
layout:setBottomMargin(591.5573)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_other:runAction(innerProject.animation)
Image_bg:addChild(FileNode_other)

--Create FileNode_device
innerCSD = require("SHDeviceInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_device = innerProject.root
FileNode_device.animation = innerProject.animation
FileNode_device:setName("FileNode_device")
FileNode_device:setTag(546)
FileNode_device:setCascadeColorEnabled(true)
FileNode_device:setCascadeOpacityEnabled(true)
FileNode_device:setPosition(959.9529, 689.8776)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_device)
layout:setPositionPercentX(0.7500)
layout:setPositionPercentY(0.9582)
layout:setLeftMargin(959.9529)
layout:setRightMargin(320.0471)
layout:setTopMargin(30.1224)
layout:setBottomMargin(689.8776)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_device:runAction(innerProject.animation)
Image_bg:addChild(FileNode_device)

--Create FileNode_menu
innerCSD = require("SHMenuNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_menu = innerProject.root
FileNode_menu.animation = innerProject.animation
FileNode_menu:setName("FileNode_menu")
FileNode_menu:setTag(553)
FileNode_menu:setCascadeColorEnabled(true)
FileNode_menu:setCascadeOpacityEnabled(true)
FileNode_menu:setPosition(1233.8930, 672.7539)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_menu)
layout:setPositionPercentX(0.9640)
layout:setPositionPercentY(0.9344)
layout:setLeftMargin(1233.8930)
layout:setRightMargin(46.1066)
layout:setTopMargin(47.2461)
layout:setBottomMargin(672.7539)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_menu:runAction(innerProject.animation)
Image_bg:addChild(FileNode_menu)

--Create FileNode_button
innerCSD = require("SHButtonGroupNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_button = innerProject.root
FileNode_button.animation = innerProject.animation
FileNode_button:setName("FileNode_button")
FileNode_button:setTag(680)
FileNode_button:setCascadeColorEnabled(true)
FileNode_button:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_button)
layout:setRightMargin(1280.0000)
layout:setTopMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_button:runAction(innerProject.animation)
Image_bg:addChild(FileNode_button)

--Create FileNode_countdown
innerCSD = require("SHGameCountDownNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_countdown = innerProject.root
FileNode_countdown.animation = innerProject.animation
FileNode_countdown:setName("FileNode_countdown")
FileNode_countdown:setTag(908)
FileNode_countdown:setCascadeColorEnabled(true)
FileNode_countdown:setCascadeOpacityEnabled(true)
FileNode_countdown:setPosition(924.8661, 422.1732)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_countdown)
layout:setPositionPercentX(0.7226)
layout:setPositionPercentY(0.5864)
layout:setLeftMargin(924.8661)
layout:setRightMargin(355.1339)
layout:setTopMargin(297.8268)
layout:setBottomMargin(422.1732)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_countdown:runAction(innerProject.animation)
Image_bg:addChild(FileNode_countdown)

--Create FileNode_tableinfo
innerCSD = require("SHTableInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_tableinfo = innerProject.root
FileNode_tableinfo.animation = innerProject.animation
FileNode_tableinfo:setName("FileNode_tableinfo")
FileNode_tableinfo:setTag(224)
FileNode_tableinfo:setCascadeColorEnabled(true)
FileNode_tableinfo:setCascadeOpacityEnabled(true)
FileNode_tableinfo:setPosition(208.7448, 489.2810)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_tableinfo)
layout:setPositionPercentX(0.1631)
layout:setPositionPercentY(0.6796)
layout:setLeftMargin(208.7448)
layout:setRightMargin(1071.2550)
layout:setTopMargin(230.7190)
layout:setBottomMargin(489.2810)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_tableinfo:runAction(innerProject.animation)
Image_bg:addChild(FileNode_tableinfo)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

