--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/mainView/sh_txkuang.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(74)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(66.4800, 1.1461)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 125.0000, height = 167.0000})
layout:setLeftMargin(3.9800)
layout:setRightMargin(-128.9800)
layout:setTopMargin(-84.6461)
layout:setBottomMargin(-82.3539)
Node:addChild(Image_bg)

--Create Image_head
local Image_head = ccui.ImageView:create()
Image_head:ignoreContentAdaptWithSize(false)
Image_head:loadTexture("game_res/mainView/sh_txkuang_2.png",0)
Image_head:setLayoutComponentEnabled(true)
Image_head:setName("Image_head")
Image_head:setTag(75)
Image_head:setCascadeColorEnabled(true)
Image_head:setCascadeOpacityEnabled(true)
Image_head:setPosition(62.8061, 82.9302)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_head)
layout:setPositionPercentX(0.5024)
layout:setPositionPercentY(0.4966)
layout:setPercentWidth(0.8000)
layout:setPercentHeight(0.5988)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(12.8061)
layout:setRightMargin(12.1939)
layout:setTopMargin(34.0698)
layout:setBottomMargin(32.9302)
Image_bg:addChild(Image_head)

--Create Text_userName
local Text_userName = ccui.Text:create()
Text_userName:ignoreContentAdaptWithSize(true)
Text_userName:setTextAreaSize({width = 0, height = 0})
Text_userName:setFontSize(18)
Text_userName:setString([[UserName]])
Text_userName:setLayoutComponentEnabled(true)
Text_userName:setName("Text_userName")
Text_userName:setTag(76)
Text_userName:setCascadeColorEnabled(true)
Text_userName:setCascadeOpacityEnabled(true)
Text_userName:setPosition(63.0208, 152.4117)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_userName)
layout:setPositionPercentX(0.5042)
layout:setPositionPercentY(0.9126)
layout:setPercentWidth(0.5760)
layout:setPercentHeight(0.1078)
layout:setSize({width = 72.0000, height = 18.0000})
layout:setLeftMargin(27.0208)
layout:setRightMargin(25.9792)
layout:setTopMargin(5.5883)
layout:setBottomMargin(143.4117)
Image_bg:addChild(Text_userName)

--Create Text_gold
local Text_gold = ccui.Text:create()
Text_gold:ignoreContentAdaptWithSize(true)
Text_gold:setTextAreaSize({width = 0, height = 0})
Text_gold:setFontSize(18)
Text_gold:setString([[1.00万]])
Text_gold:setLayoutComponentEnabled(true)
Text_gold:setName("Text_gold")
Text_gold:setTag(77)
Text_gold:setCascadeColorEnabled(true)
Text_gold:setCascadeOpacityEnabled(true)
Text_gold:setPosition(61.5303, 13.4075)
Text_gold:setTextColor({r = 255, g = 210, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gold)
layout:setPositionPercentX(0.4922)
layout:setPositionPercentY(0.0803)
layout:setPercentWidth(0.4320)
layout:setPercentHeight(0.1078)
layout:setSize({width = 54.0000, height = 18.0000})
layout:setLeftMargin(34.5303)
layout:setRightMargin(36.4697)
layout:setTopMargin(144.5925)
layout:setBottomMargin(4.4075)
Image_bg:addChild(Text_gold)

--Create Image_gamebet
local Image_gamebet = ccui.ImageView:create()
Image_gamebet:ignoreContentAdaptWithSize(false)
Image_gamebet:loadTexture("game_res/mainView/sh_cmkuang.png",0)
Image_gamebet:setLayoutComponentEnabled(true)
Image_gamebet:setName("Image_gamebet")
Image_gamebet:setTag(78)
Image_gamebet:setCascadeColorEnabled(true)
Image_gamebet:setCascadeOpacityEnabled(true)
Image_gamebet:setPosition(200.0000, 185.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_gamebet)
layout:setPositionPercentX(1.6000)
layout:setPositionPercentY(1.1078)
layout:setPercentWidth(1.0160)
layout:setPercentHeight(0.1737)
layout:setSize({width = 127.0000, height = 29.0000})
layout:setLeftMargin(136.5000)
layout:setRightMargin(-138.5000)
layout:setTopMargin(-32.5000)
layout:setBottomMargin(170.5000)
Image_bg:addChild(Image_gamebet)

--Create AtlasLabel_gamebet
local AtlasLabel_gamebet = ccui.TextAtlas:create([[0]],
													"game_res/mainView/sh_szt_2.png",
													13,
													17,
													"/")
AtlasLabel_gamebet:setLayoutComponentEnabled(true)
AtlasLabel_gamebet:setName("AtlasLabel_gamebet")
AtlasLabel_gamebet:setTag(79)
AtlasLabel_gamebet:setCascadeColorEnabled(true)
AtlasLabel_gamebet:setCascadeOpacityEnabled(true)
AtlasLabel_gamebet:setAnchorPoint(1.0000, 0.5000)
AtlasLabel_gamebet:setPosition(109.9471, 14.4738)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_gamebet)
layout:setPositionPercentX(0.8657)
layout:setPositionPercentY(0.4991)
layout:setPercentWidth(0.1024)
layout:setPercentHeight(0.5862)
layout:setSize({width = 13.0000, height = 17.0000})
layout:setLeftMargin(96.9471)
layout:setRightMargin(17.0529)
layout:setTopMargin(6.0262)
layout:setBottomMargin(5.9738)
Image_gamebet:addChild(AtlasLabel_gamebet)

--Create Image_roundbet
local Image_roundbet = ccui.ImageView:create()
Image_roundbet:ignoreContentAdaptWithSize(false)
Image_roundbet:loadTexture("game_res/mainView/sh_cmkuang_2.png",0)
Image_roundbet:setScale9Enabled(true)
Image_roundbet:setCapInsets({x = 41, y = 9, width = 45, height = 11})
Image_roundbet:setLayoutComponentEnabled(true)
Image_roundbet:setName("Image_roundbet")
Image_roundbet:setTag(80)
Image_roundbet:setCascadeColorEnabled(true)
Image_roundbet:setCascadeOpacityEnabled(true)
Image_roundbet:setAnchorPoint(0.0000, 0.5000)
Image_roundbet:setPosition(286.5000, 185.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_roundbet)
layout:setPositionPercentX(2.2920)
layout:setPositionPercentY(1.1078)
layout:setPercentWidth(1.0160)
layout:setPercentHeight(0.1737)
layout:setSize({width = 127.0000, height = 29.0000})
layout:setLeftMargin(286.5000)
layout:setRightMargin(-288.5000)
layout:setTopMargin(-32.5000)
layout:setBottomMargin(170.5000)
Image_bg:addChild(Image_roundbet)

--Create Image_roundtag
local Image_roundtag = ccui.ImageView:create()
Image_roundtag:ignoreContentAdaptWithSize(false)
Image_roundtag:loadTexture("game_res/mainView/sh_jiazhu.png",0)
Image_roundtag:setLayoutComponentEnabled(true)
Image_roundtag:setName("Image_roundtag")
Image_roundtag:setTag(81)
Image_roundtag:setCascadeColorEnabled(true)
Image_roundtag:setCascadeOpacityEnabled(true)
Image_roundtag:setPosition(30.6342, 14.2683)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_roundtag)
layout:setPositionPercentX(0.2412)
layout:setPositionPercentY(0.4920)
layout:setPercentWidth(0.3465)
layout:setPercentHeight(0.6552)
layout:setSize({width = 44.0000, height = 19.0000})
layout:setLeftMargin(8.6342)
layout:setRightMargin(74.3658)
layout:setTopMargin(5.2317)
layout:setBottomMargin(4.7683)
Image_roundbet:addChild(Image_roundtag)

--Create AtlasLabel_roundbet
local AtlasLabel_roundbet = ccui.TextAtlas:create([[0]],
													"game_res/mainView/sh_szt_1.png",
													13,
													17,
													"/")
AtlasLabel_roundbet:setLayoutComponentEnabled(true)
AtlasLabel_roundbet:setName("AtlasLabel_roundbet")
AtlasLabel_roundbet:setTag(82)
AtlasLabel_roundbet:setCascadeColorEnabled(true)
AtlasLabel_roundbet:setCascadeOpacityEnabled(true)
AtlasLabel_roundbet:setAnchorPoint(0.0000, 0.5000)
AtlasLabel_roundbet:setPosition(58.2859, 13.9001)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_roundbet)
layout:setPositionPercentX(0.4589)
layout:setPositionPercentY(0.4793)
layout:setPercentWidth(0.1024)
layout:setPercentHeight(0.5862)
layout:setSize({width = 13.0000, height = 17.0000})
layout:setLeftMargin(58.2859)
layout:setRightMargin(55.7141)
layout:setTopMargin(6.5999)
layout:setBottomMargin(5.4001)
Image_roundbet:addChild(AtlasLabel_roundbet)

--Create FileNode_1
innerCSD = require("SHPokerNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(83)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(200.0000, 80.0000)
FileNode_1:setScaleX(0.7000)
FileNode_1:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentX(1.6000)
layout:setPositionPercentY(0.4790)
layout:setLeftMargin(200.0000)
layout:setRightMargin(-75.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(80.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Image_bg:addChild(FileNode_1)

--Create FileNode_2
innerCSD = require("SHPokerNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_2 = innerProject.root
FileNode_2.animation = innerProject.animation
FileNode_2:setName("FileNode_2")
FileNode_2:setTag(88)
FileNode_2:setCascadeColorEnabled(true)
FileNode_2:setCascadeOpacityEnabled(true)
FileNode_2:setPosition(250.0000, 80.0000)
FileNode_2:setScaleX(0.7000)
FileNode_2:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_2)
layout:setPositionPercentX(2.0000)
layout:setPositionPercentY(0.4790)
layout:setLeftMargin(250.0000)
layout:setRightMargin(-125.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(80.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_2:runAction(innerProject.animation)
Image_bg:addChild(FileNode_2)

--Create FileNode_3
innerCSD = require("SHPokerNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_3 = innerProject.root
FileNode_3.animation = innerProject.animation
FileNode_3:setName("FileNode_3")
FileNode_3:setTag(93)
FileNode_3:setCascadeColorEnabled(true)
FileNode_3:setCascadeOpacityEnabled(true)
FileNode_3:setPosition(300.0000, 80.0000)
FileNode_3:setScaleX(0.7000)
FileNode_3:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_3)
layout:setPositionPercentX(2.4000)
layout:setPositionPercentY(0.4790)
layout:setLeftMargin(300.0000)
layout:setRightMargin(-175.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(80.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_3:runAction(innerProject.animation)
Image_bg:addChild(FileNode_3)

--Create FileNode_4
innerCSD = require("SHPokerNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_4 = innerProject.root
FileNode_4.animation = innerProject.animation
FileNode_4:setName("FileNode_4")
FileNode_4:setTag(98)
FileNode_4:setCascadeColorEnabled(true)
FileNode_4:setCascadeOpacityEnabled(true)
FileNode_4:setPosition(350.0000, 80.0000)
FileNode_4:setScaleX(0.7000)
FileNode_4:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_4)
layout:setPositionPercentX(2.8000)
layout:setPositionPercentY(0.4790)
layout:setLeftMargin(350.0000)
layout:setRightMargin(-225.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(80.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_4:runAction(innerProject.animation)
Image_bg:addChild(FileNode_4)

--Create FileNode_5
innerCSD = require("SHPokerNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_5 = innerProject.root
FileNode_5.animation = innerProject.animation
FileNode_5:setName("FileNode_5")
FileNode_5:setTag(103)
FileNode_5:setCascadeColorEnabled(true)
FileNode_5:setCascadeOpacityEnabled(true)
FileNode_5:setPosition(400.0000, 80.0000)
FileNode_5:setScaleX(0.7000)
FileNode_5:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_5)
layout:setPositionPercentX(3.2000)
layout:setPositionPercentY(0.4790)
layout:setLeftMargin(400.0000)
layout:setRightMargin(-275.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(80.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_5:runAction(innerProject.animation)
Image_bg:addChild(FileNode_5)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

