--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg_panel
local bg_panel = ccui.Layout:create()
bg_panel:ignoreContentAdaptWithSize(false)
bg_panel:setClippingEnabled(false)
bg_panel:setBackGroundColorType(1)
bg_panel:setBackGroundColor({r = 0, g = 0, b = 0})
bg_panel:setBackGroundColorOpacity(127)
bg_panel:setTouchEnabled(true);
bg_panel:setLayoutComponentEnabled(true)
bg_panel:setName("bg_panel")
bg_panel:setTag(56)
bg_panel:setCascadeColorEnabled(true)
bg_panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_panel)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg_panel)

--Create alert_view
local alert_view = ccui.Layout:create()
alert_view:ignoreContentAdaptWithSize(false)
alert_view:setBackGroundImage("hall_res/tongyong/bb_ty_tc.png",0)
alert_view:setClippingEnabled(false)
alert_view:setBackGroundColorOpacity(102)
alert_view:setTouchEnabled(true);
alert_view:setLayoutComponentEnabled(true)
alert_view:setName("alert_view")
alert_view:setTag(57)
alert_view:setCascadeColorEnabled(true)
alert_view:setCascadeOpacityEnabled(true)
alert_view:setAnchorPoint(0.5000, 0.5000)
alert_view:setPosition(641.1520, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alert_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5009)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8008)
layout:setPercentHeight(0.8806)
layout:setSize({width = 1025.0000, height = 634.0000})
layout:setLeftMargin(128.6520)
layout:setRightMargin(126.3480)
layout:setTopMargin(43.0000)
layout:setBottomMargin(43.0000)
bg_panel:addChild(alert_view)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("hall_res/account_bind_tip/bb_khyj_di.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(58)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(514.0375, 385.9792)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5015)
layout:setPositionPercentY(0.6088)
layout:setPercentWidth(0.7551)
layout:setPercentHeight(0.6356)
layout:setSize({width = 774.0000, height = 403.0000})
layout:setLeftMargin(127.0375)
layout:setRightMargin(123.9625)
layout:setTopMargin(46.5208)
layout:setBottomMargin(184.4792)
alert_view:addChild(Image_1)

--Create Image_title
local Image_title = ccui.ImageView:create()
Image_title:ignoreContentAdaptWithSize(false)
Image_title:loadTexture("hall_res/account_bind_tip/bb_khyj_bt.png",0)
Image_title:setLayoutComponentEnabled(true)
Image_title:setName("Image_title")
Image_title:setTag(29)
Image_title:setCascadeColorEnabled(true)
Image_title:setCascadeOpacityEnabled(true)
Image_title:setPosition(480.5200, 607.9742)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4688)
layout:setPositionPercentY(0.9589)
layout:setPercentWidth(0.7005)
layout:setPercentHeight(0.2965)
layout:setSize({width = 718.0000, height = 188.0000})
layout:setLeftMargin(121.5200)
layout:setRightMargin(185.4800)
layout:setTopMargin(-67.9742)
layout:setBottomMargin(513.9742)
alert_view:addChild(Image_title)

--Create Image_content1
local Image_content1 = ccui.ImageView:create()
Image_content1:ignoreContentAdaptWithSize(false)
Image_content1:loadTexture("hall_res/account_bind_tip/bb_khyj_zi.png",0)
Image_content1:setLayoutComponentEnabled(true)
Image_content1:setName("Image_content1")
Image_content1:setTag(30)
Image_content1:setCascadeColorEnabled(true)
Image_content1:setCascadeOpacityEnabled(true)
Image_content1:setPosition(514.0375, 385.9792)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_content1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5015)
layout:setPositionPercentY(0.6088)
layout:setPercentWidth(0.5746)
layout:setPercentHeight(0.2208)
layout:setSize({width = 589.0000, height = 140.0000})
layout:setLeftMargin(219.5375)
layout:setRightMargin(216.4625)
layout:setTopMargin(178.0208)
layout:setBottomMargin(315.9792)
alert_view:addChild(Image_content1)

--Create canel_btn
local canel_btn = ccui.Button:create()
canel_btn:ignoreContentAdaptWithSize(false)
canel_btn:loadTextureNormal("hall_res/account_bind_tip/bb_khyj_xww.png",0)
canel_btn:loadTexturePressed("hall_res/account_bind_tip/bb_khyj_xww1.png",0)
canel_btn:loadTextureDisabled("hall_res/account_bind_tip/bb_khyj_xww1.png",0)
canel_btn:setTitleFontSize(14)
canel_btn:setTitleColor({r = 65, g = 65, b = 70})
canel_btn:setScale9Enabled(true)
canel_btn:setCapInsets({x = 15, y = 11, width = 257, height = 78})
canel_btn:setLayoutComponentEnabled(true)
canel_btn:setName("canel_btn")
canel_btn:setTag(60)
canel_btn:setCascadeColorEnabled(true)
canel_btn:setCascadeOpacityEnabled(true)
canel_btn:setPosition(307.5000, 130.5200)
layout = ccui.LayoutComponent:bindLayoutComponent(canel_btn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.2059)
layout:setPercentWidth(0.2800)
layout:setPercentHeight(0.1577)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(164.0000)
layout:setRightMargin(574.0000)
layout:setTopMargin(453.4800)
layout:setBottomMargin(80.5200)
alert_view:addChild(canel_btn)

--Create bind_btn
local bind_btn = ccui.Button:create()
bind_btn:ignoreContentAdaptWithSize(false)
bind_btn:loadTextureNormal("hall_res/account_bind_tip/bb_khyj_qbd.png",0)
bind_btn:loadTexturePressed("hall_res/account_bind_tip/bb_khyj_qbd1.png",0)
bind_btn:loadTextureDisabled("hall_res/account_bind_tip/bb_khyj_qbd1.png",0)
bind_btn:setTitleFontSize(14)
bind_btn:setTitleColor({r = 65, g = 65, b = 70})
bind_btn:setScale9Enabled(true)
bind_btn:setCapInsets({x = 15, y = 11, width = 257, height = 78})
bind_btn:setLayoutComponentEnabled(true)
bind_btn:setName("bind_btn")
bind_btn:setTag(59)
bind_btn:setCascadeColorEnabled(true)
bind_btn:setCascadeOpacityEnabled(true)
bind_btn:setPosition(717.5000, 130.5200)
layout = ccui.LayoutComponent:bindLayoutComponent(bind_btn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.2059)
layout:setPercentWidth(0.2800)
layout:setPercentHeight(0.1577)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(574.0000)
layout:setRightMargin(164.0000)
layout:setTopMargin(453.4800)
layout:setBottomMargin(80.5200)
alert_view:addChild(bind_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

