--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create alipay_account
local alipay_account=cc.Node:create()
alipay_account:setName("alipay_account")
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_account)
layout:setSize({width = 950.0000, height = 620.0000})

--Create alipay_bind_view
local alipay_bind_view = ccui.Layout:create()
alipay_bind_view:ignoreContentAdaptWithSize(false)
alipay_bind_view:setClippingEnabled(false)
alipay_bind_view:setBackGroundColorOpacity(102)
alipay_bind_view:setTouchEnabled(true);
alipay_bind_view:setLayoutComponentEnabled(true)
alipay_bind_view:setName("alipay_bind_view")
alipay_bind_view:setTag(220)
alipay_bind_view:setCascadeColorEnabled(true)
alipay_bind_view:setCascadeOpacityEnabled(true)
alipay_bind_view:setAnchorPoint(0.0000, 1.0000)
alipay_bind_view:setPosition(0.0000, 620.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_bind_view)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 950.0000, height = 620.0000})
alipay_account:addChild(alipay_bind_view)

--Create Image_52
local Image_52 = ccui.ImageView:create()
Image_52:ignoreContentAdaptWithSize(false)
Image_52:loadTexture("hall_res/account/bb_grxx_ljbd_zhifubao.png",0)
Image_52:setLayoutComponentEnabled(true)
Image_52:setName("Image_52")
Image_52:setTag(221)
Image_52:setCascadeColorEnabled(true)
Image_52:setCascadeOpacityEnabled(true)
Image_52:setPosition(512.3156, 447.0673)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_52)
layout:setPositionPercentX(0.5393)
layout:setPositionPercentY(0.7211)
layout:setPercentWidth(0.5568)
layout:setPercentHeight(0.2613)
layout:setSize({width = 529.0000, height = 162.0000})
layout:setLeftMargin(247.8156)
layout:setRightMargin(173.1844)
layout:setTopMargin(91.9327)
layout:setBottomMargin(366.0673)
alipay_bind_view:addChild(Image_52)

--Create alipay_name__panel
local alipay_name__panel = ccui.Layout:create()
alipay_name__panel:ignoreContentAdaptWithSize(false)
alipay_name__panel:setClippingEnabled(false)
alipay_name__panel:setBackGroundColorOpacity(102)
alipay_name__panel:setTouchEnabled(true);
alipay_name__panel:setLayoutComponentEnabled(true)
alipay_name__panel:setName("alipay_name__panel")
alipay_name__panel:setTag(222)
alipay_name__panel:setCascadeColorEnabled(true)
alipay_name__panel:setCascadeOpacityEnabled(true)
alipay_name__panel:setAnchorPoint(0.0000, 0.5000)
alipay_name__panel:setPosition(113.2656, 330.3676)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_name__panel)
layout:setPositionPercentX(0.1192)
layout:setPositionPercentY(0.5329)
layout:setPercentWidth(0.8032)
layout:setPercentHeight(0.0919)
layout:setSize({width = 763.0000, height = 57.0000})
layout:setLeftMargin(113.2656)
layout:setRightMargin(73.7344)
layout:setTopMargin(261.1324)
layout:setBottomMargin(301.8676)
alipay_bind_view:addChild(alipay_name__panel)

--Create Image_24
local Image_24 = ccui.ImageView:create()
Image_24:ignoreContentAdaptWithSize(false)
Image_24:loadTexture("Default/ImageFile.png",0)
Image_24:setLayoutComponentEnabled(true)
Image_24:setName("Image_24")
Image_24:setTag(223)
Image_24:setCascadeColorEnabled(true)
Image_24:setCascadeOpacityEnabled(true)
Image_24:setAnchorPoint(1.0000, 0.5000)
Image_24:setPosition(180.0000, 30.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_24)
layout:setPositionPercentX(0.2359)
layout:setPositionPercentY(0.5351)
layout:setPercentWidth(0.2988)
layout:setPercentHeight(0.9474)
layout:setSize({width = 228.0000, height = 54.0000})
layout:setLeftMargin(-48.0000)
layout:setRightMargin(583.0000)
layout:setTopMargin(-0.5000)
layout:setBottomMargin(3.5000)
alipay_name__panel:addChild(Image_24)

--Create alipay_name_bg
local alipay_name_bg = ccui.ImageView:create()
alipay_name_bg:ignoreContentAdaptWithSize(false)
alipay_name_bg:loadTexture("hall_res/account/bb_grxx_KK.png",0)
alipay_name_bg:setLayoutComponentEnabled(true)
alipay_name_bg:setName("alipay_name_bg")
alipay_name_bg:setTag(224)
alipay_name_bg:setCascadeColorEnabled(true)
alipay_name_bg:setCascadeOpacityEnabled(true)
alipay_name_bg:setAnchorPoint(0.0000, 0.5000)
alipay_name_bg:setPosition(180.0000, 28.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_name_bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2359)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6540)
layout:setPercentHeight(1.3158)
layout:setSize({width = 499.0000, height = 75.0000})
layout:setLeftMargin(180.0000)
layout:setRightMargin(84.0000)
layout:setTopMargin(-9.0000)
layout:setBottomMargin(-9.0000)
alipay_name__panel:addChild(alipay_name_bg)

--Create alipay_name_text
local alipay_name_text = ccui.Text:create()
alipay_name_text:ignoreContentAdaptWithSize(false)
alipay_name_text:setFontSize(40)
alipay_name_text:setString([[+9618587463458]])
alipay_name_text:enableShadow({r = 255, g = 255, b = 255, a = 255}, {width = 0, height = 0}, 0)
alipay_name_text:setLayoutComponentEnabled(true)
alipay_name_text:setName("alipay_name_text")
alipay_name_text:setTag(225)
alipay_name_text:setCascadeColorEnabled(true)
alipay_name_text:setCascadeOpacityEnabled(true)
alipay_name_text:setAnchorPoint(0.0000, 0.5000)
alipay_name_text:setPosition(19.0000, 37.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_name_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0381)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0922)
layout:setPercentHeight(0.5333)
layout:setSize({width = 545.0000, height = 40.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(17.5000)
layout:setBottomMargin(17.5000)
alipay_name_bg:addChild(alipay_name_text)

--Create alipay_account_panel
local alipay_account_panel = ccui.Layout:create()
alipay_account_panel:ignoreContentAdaptWithSize(false)
alipay_account_panel:setClippingEnabled(false)
alipay_account_panel:setBackGroundColorOpacity(102)
alipay_account_panel:setTouchEnabled(true);
alipay_account_panel:setLayoutComponentEnabled(true)
alipay_account_panel:setName("alipay_account_panel")
alipay_account_panel:setTag(226)
alipay_account_panel:setCascadeColorEnabled(true)
alipay_account_panel:setCascadeOpacityEnabled(true)
alipay_account_panel:setAnchorPoint(0.0000, 0.5000)
alipay_account_panel:setPosition(293.2654, 242.3678)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_account_panel)
layout:setPositionPercentX(0.3087)
layout:setPositionPercentY(0.3909)
layout:setPercentWidth(0.6137)
layout:setPercentHeight(0.0919)
layout:setSize({width = 583.0000, height = 57.0000})
layout:setLeftMargin(293.2654)
layout:setRightMargin(73.7346)
layout:setTopMargin(349.1322)
layout:setBottomMargin(213.8678)
alipay_bind_view:addChild(alipay_account_panel)

--Create Image_24
local Image_24 = ccui.ImageView:create()
Image_24:ignoreContentAdaptWithSize(false)
Image_24:loadTexture("Default/ImageFile.png",0)
Image_24:setLayoutComponentEnabled(true)
Image_24:setName("Image_24")
Image_24:setTag(227)
Image_24:setCascadeColorEnabled(true)
Image_24:setCascadeOpacityEnabled(true)
Image_24:setAnchorPoint(1.0000, 0.5000)
Image_24:setPosition(0.0001, 30.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_24)
layout:setPositionPercentY(0.5351)
layout:setPercentWidth(0.3945)
layout:setPercentHeight(0.9474)
layout:setSize({width = 230.0000, height = 54.0000})
layout:setLeftMargin(-229.9999)
layout:setRightMargin(582.9999)
layout:setTopMargin(-0.5000)
layout:setBottomMargin(3.5000)
alipay_account_panel:addChild(Image_24)

--Create alipay_account_bg
local alipay_account_bg = ccui.ImageView:create()
alipay_account_bg:ignoreContentAdaptWithSize(false)
alipay_account_bg:loadTexture("hall_res/account/bb_grxx_KK.png",0)
alipay_account_bg:setLayoutComponentEnabled(true)
alipay_account_bg:setName("alipay_account_bg")
alipay_account_bg:setTag(228)
alipay_account_bg:setCascadeColorEnabled(true)
alipay_account_bg:setCascadeOpacityEnabled(true)
alipay_account_bg:setAnchorPoint(0.0000, 0.5000)
alipay_account_bg:setPosition(0.0000, 28.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_account_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8559)
layout:setPercentHeight(1.3158)
layout:setSize({width = 499.0000, height = 75.0000})
layout:setRightMargin(84.0000)
layout:setTopMargin(-9.0000)
layout:setBottomMargin(-9.0000)
alipay_account_panel:addChild(alipay_account_bg)

--Create alipay_account_text
local alipay_account_text = ccui.Text:create()
alipay_account_text:ignoreContentAdaptWithSize(false)
alipay_account_text:setFontSize(40)
alipay_account_text:setString([[+9618587463458]])
alipay_account_text:enableShadow({r = 255, g = 255, b = 255, a = 255}, {width = 0, height = 0}, 0)
alipay_account_text:setLayoutComponentEnabled(true)
alipay_account_text:setName("alipay_account_text")
alipay_account_text:setTag(229)
alipay_account_text:setCascadeColorEnabled(true)
alipay_account_text:setCascadeOpacityEnabled(true)
alipay_account_text:setAnchorPoint(0.0000, 0.5000)
alipay_account_text:setPosition(19.0000, 37.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(alipay_account_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0381)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0922)
layout:setPercentHeight(0.5333)
layout:setSize({width = 545.0000, height = 40.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(-65.0000)
layout:setTopMargin(17.5000)
layout:setBottomMargin(17.5000)
alipay_account_bg:addChild(alipay_account_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = alipay_account
return result;
end

return Result

