--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(106)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create FileNode_1
innerCSD = require("PublicTopInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(461)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(0.0000, 720.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(1.0000)
layout:setRightMargin(1280.0000)
layout:setBottomMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Panel_1:addChild(FileNode_1)

--Create Image_51
local Image_51 = ccui.ImageView:create()
Image_51:ignoreContentAdaptWithSize(false)
Image_51:loadTexture("hall_res/tongyong/bb_ty_zuodi.png",0)
Image_51:setLayoutComponentEnabled(true)
Image_51:setName("Image_51")
Image_51:setTag(223)
Image_51:setCascadeColorEnabled(true)
Image_51:setCascadeOpacityEnabled(true)
Image_51:setAnchorPoint(0.0000, 0.5000)
Image_51:setPosition(0.0000, 312.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_51)
layout:setPositionPercentY(0.4333)
layout:setPercentWidth(0.2047)
layout:setPercentHeight(0.8861)
layout:setSize({width = 262.0000, height = 638.0000})
layout:setRightMargin(1018.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(-7.0000)
Panel_1:addChild(Image_51)

--Create view_btn_listview
local view_btn_listview = ccui.ListView:create()
view_btn_listview:setItemsMargin(10)
view_btn_listview:setDirection(1)
view_btn_listview:setGravity(0)
view_btn_listview:ignoreContentAdaptWithSize(false)
view_btn_listview:setClippingEnabled(false)
view_btn_listview:setBackGroundColorOpacity(102)
view_btn_listview:setLayoutComponentEnabled(true)
view_btn_listview:setName("view_btn_listview")
view_btn_listview:setTag(110)
view_btn_listview:setCascadeColorEnabled(true)
view_btn_listview:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(view_btn_listview)
layout:setPercentWidth(0.2148)
layout:setPercentHeight(0.8667)
layout:setSize({width = 275.0000, height = 624.0000})
layout:setRightMargin(1005.0000)
layout:setTopMargin(96.0000)
Panel_1:addChild(view_btn_listview)

--Create bank_deposit_view_btn
local bank_deposit_view_btn = ccui.Button:create()
bank_deposit_view_btn:ignoreContentAdaptWithSize(false)
bank_deposit_view_btn:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_cr1.png",0)
bank_deposit_view_btn:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_cr.png",0)
bank_deposit_view_btn:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_cr.png",0)
bank_deposit_view_btn:setTitleFontSize(14)
bank_deposit_view_btn:setTitleColor({r = 65, g = 65, b = 70})
bank_deposit_view_btn:setScale9Enabled(true)
bank_deposit_view_btn:setCapInsets({x = 15, y = 11, width = 240, height = 58})
bank_deposit_view_btn:setLayoutComponentEnabled(true)
bank_deposit_view_btn:setName("bank_deposit_view_btn")
bank_deposit_view_btn:setTag(111)
bank_deposit_view_btn:setCascadeColorEnabled(true)
bank_deposit_view_btn:setCascadeOpacityEnabled(true)
bank_deposit_view_btn:setAnchorPoint(0.0000, 0.5000)
bank_deposit_view_btn:setPosition(0.0000, 584.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bank_deposit_view_btn)
layout:setPositionPercentY(0.9359)
layout:setPercentWidth(0.9818)
layout:setPercentHeight(0.1282)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(5.0000)
layout:setBottomMargin(544.0000)
view_btn_listview:pushBackCustomItem(bank_deposit_view_btn)

--Create bank_viewdraw_view_btn
local bank_viewdraw_view_btn = ccui.Button:create()
bank_viewdraw_view_btn:ignoreContentAdaptWithSize(false)
bank_viewdraw_view_btn:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_qc1.png",0)
bank_viewdraw_view_btn:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_qc.png",0)
bank_viewdraw_view_btn:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_qc.png",0)
bank_viewdraw_view_btn:setTitleFontSize(14)
bank_viewdraw_view_btn:setTitleColor({r = 65, g = 65, b = 70})
bank_viewdraw_view_btn:setScale9Enabled(true)
bank_viewdraw_view_btn:setCapInsets({x = 15, y = 11, width = 240, height = 58})
bank_viewdraw_view_btn:setLayoutComponentEnabled(true)
bank_viewdraw_view_btn:setName("bank_viewdraw_view_btn")
bank_viewdraw_view_btn:setLocalZOrder(1)
bank_viewdraw_view_btn:setTag(135)
bank_viewdraw_view_btn:setCascadeColorEnabled(true)
bank_viewdraw_view_btn:setCascadeOpacityEnabled(true)
bank_viewdraw_view_btn:setAnchorPoint(0.0000, 0.5000)
bank_viewdraw_view_btn:setPosition(0.0000, 494.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bank_viewdraw_view_btn)
layout:setPositionPercentY(0.7917)
layout:setPercentWidth(0.9818)
layout:setPercentHeight(0.1282)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(5.0000)
layout:setTopMargin(90.0000)
layout:setBottomMargin(454.0000)
view_btn_listview:pushBackCustomItem(bank_viewdraw_view_btn)

--Create transfer_accounts_view_btn
local transfer_accounts_view_btn = ccui.Button:create()
transfer_accounts_view_btn:ignoreContentAdaptWithSize(false)
transfer_accounts_view_btn:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_zz1.png",0)
transfer_accounts_view_btn:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_zz1.png",0)
transfer_accounts_view_btn:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_zz.png",0)
transfer_accounts_view_btn:setTitleFontSize(14)
transfer_accounts_view_btn:setTitleColor({r = 65, g = 65, b = 70})
transfer_accounts_view_btn:setScale9Enabled(true)
transfer_accounts_view_btn:setCapInsets({x = 15, y = 11, width = 240, height = 58})
transfer_accounts_view_btn:setLayoutComponentEnabled(true)
transfer_accounts_view_btn:setName("transfer_accounts_view_btn")
transfer_accounts_view_btn:setLocalZOrder(2)
transfer_accounts_view_btn:setTag(136)
transfer_accounts_view_btn:setCascadeColorEnabled(true)
transfer_accounts_view_btn:setCascadeOpacityEnabled(true)
transfer_accounts_view_btn:setAnchorPoint(0.0000, 0.5000)
transfer_accounts_view_btn:setPosition(0.0000, 404.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(transfer_accounts_view_btn)
layout:setPositionPercentY(0.6474)
layout:setPercentWidth(0.9818)
layout:setPercentHeight(0.1282)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(5.0000)
layout:setTopMargin(180.0000)
layout:setBottomMargin(364.0000)
view_btn_listview:pushBackCustomItem(transfer_accounts_view_btn)

--Create sub_view_parent
local sub_view_parent = ccui.Layout:create()
sub_view_parent:ignoreContentAdaptWithSize(false)
sub_view_parent:setClippingEnabled(false)
sub_view_parent:setBackGroundColorOpacity(102)
sub_view_parent:setTouchEnabled(true);
sub_view_parent:setLayoutComponentEnabled(true)
sub_view_parent:setName("sub_view_parent")
sub_view_parent:setTag(39)
sub_view_parent:setCascadeColorEnabled(true)
sub_view_parent:setCascadeOpacityEnabled(true)
sub_view_parent:setAnchorPoint(0.0000, 1.0000)
sub_view_parent:setPosition(270.2027, 626.3999)
layout = ccui.LayoutComponent:bindLayoutComponent(sub_view_parent)
layout:setPositionPercentX(0.2111)
layout:setPositionPercentY(0.8700)
layout:setPercentWidth(0.7422)
layout:setPercentHeight(0.8611)
layout:setSize({width = 950.0000, height = 620.0000})
layout:setLeftMargin(270.2027)
layout:setRightMargin(59.7974)
layout:setTopMargin(93.6001)
layout:setBottomMargin(6.3999)
Panel_1:addChild(sub_view_parent)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

