--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg_panel
local bg_panel = ccui.Layout:create()
bg_panel:ignoreContentAdaptWithSize(false)
bg_panel:setClippingEnabled(false)
bg_panel:setBackGroundColorType(1)
bg_panel:setBackGroundColor({r = 0, g = 0, b = 0})
bg_panel:setBackGroundColorOpacity(127)
bg_panel:setTouchEnabled(true);
bg_panel:setLayoutComponentEnabled(true)
bg_panel:setName("bg_panel")
bg_panel:setTag(24)
bg_panel:setCascadeColorEnabled(true)
bg_panel:setCascadeOpacityEnabled(true)
bg_panel:setAnchorPoint(0.5000, 0.5000)
bg_panel:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg_panel)

--Create background
local background = ccui.ImageView:create()
background:ignoreContentAdaptWithSize(false)
background:loadTexture("hall_res/tongyong/bb_ty_tc.png",0)
background:setLayoutComponentEnabled(true)
background:setName("background")
background:setTag(86)
background:setCascadeColorEnabled(true)
background:setCascadeOpacityEnabled(true)
background:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(background)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8008)
layout:setPercentHeight(0.8806)
layout:setSize({width = 1025.0000, height = 634.0000})
layout:setLeftMargin(127.5000)
layout:setRightMargin(127.5000)
layout:setTopMargin(43.0000)
layout:setBottomMargin(43.0000)
Layer:addChild(background)

--Create bg_content
local bg_content = ccui.Layout:create()
bg_content:ignoreContentAdaptWithSize(false)
bg_content:setClippingEnabled(false)
bg_content:setBackGroundColorOpacity(102)
bg_content:setTouchEnabled(true);
bg_content:setLayoutComponentEnabled(true)
bg_content:setName("bg_content")
bg_content:setTag(89)
bg_content:setCascadeColorEnabled(true)
bg_content:setCascadeOpacityEnabled(true)
bg_content:setAnchorPoint(0.5000, 0.5000)
bg_content:setPosition(512.5000, 280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_content)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4416)
layout:setPercentWidth(0.9366)
layout:setPercentHeight(0.7571)
layout:setSize({width = 960.0000, height = 480.0000})
layout:setLeftMargin(32.5000)
layout:setRightMargin(32.5000)
layout:setTopMargin(114.0000)
layout:setBottomMargin(40.0000)
background:addChild(bg_content)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("hall_res/tongyong/bb_ty_gb.png",0)
btn_close:loadTexturePressed("Default/Button_Press.png",0)
btn_close:loadTextureDisabled("Default/Button_Disable.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 37, height = 46})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(87)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(990.0000, 584.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9659)
layout:setPositionPercentY(0.9211)
layout:setPercentWidth(0.0654)
layout:setPercentHeight(0.1073)
layout:setSize({width = 67.0000, height = 68.0000})
layout:setLeftMargin(956.5000)
layout:setRightMargin(1.5000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(550.0000)
background:addChild(btn_close)

--Create icon_title
local icon_title = ccui.ImageView:create()
icon_title:ignoreContentAdaptWithSize(false)
icon_title:loadTexture("hall_res/notice_service_setting/baobo_popupview_title_kefu.png",0)
icon_title:setLayoutComponentEnabled(true)
icon_title:setName("icon_title")
icon_title:setTag(88)
icon_title:setCascadeColorEnabled(true)
icon_title:setCascadeOpacityEnabled(true)
icon_title:setPosition(512.5000, 589.6200)
layout = ccui.LayoutComponent:bindLayoutComponent(icon_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9300)
layout:setPercentWidth(0.2137)
layout:setPercentHeight(0.0946)
layout:setSize({width = 219.0000, height = 60.0000})
layout:setLeftMargin(403.0000)
layout:setRightMargin(403.0000)
layout:setTopMargin(14.3800)
layout:setBottomMargin(559.6200)
background:addChild(icon_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

