--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg_panel
local bg_panel = ccui.Layout:create()
bg_panel:ignoreContentAdaptWithSize(false)
bg_panel:setClippingEnabled(false)
bg_panel:setBackGroundColorType(1)
bg_panel:setBackGroundColor({r = 0, g = 0, b = 0})
bg_panel:setBackGroundColorOpacity(127)
bg_panel:setTouchEnabled(true);
bg_panel:setLayoutComponentEnabled(true)
bg_panel:setName("bg_panel")
bg_panel:setTag(268)
bg_panel:setCascadeColorEnabled(true)
bg_panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_panel)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg_panel)

--Create alert_view
local alert_view = ccui.Layout:create()
alert_view:ignoreContentAdaptWithSize(false)
alert_view:setClippingEnabled(false)
alert_view:setBackGroundColorOpacity(102)
alert_view:setTouchEnabled(true);
alert_view:setLayoutComponentEnabled(true)
alert_view:setName("alert_view")
alert_view:setTag(269)
alert_view:setCascadeColorEnabled(true)
alert_view:setCascadeOpacityEnabled(true)
alert_view:setAnchorPoint(0.5000, 0.5000)
alert_view:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alert_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(0.6492)
layout:setPercentHeight(0.6806)
layout:setSize({width = 830.9760, height = 490.0000})
layout:setLeftMargin(224.5120)
layout:setRightMargin(224.5120)
layout:setTopMargin(115.0000)
layout:setBottomMargin(115.0000)
bg_panel:addChild(alert_view)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("hall_res/tongyong/bb_ty_tc1.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(270)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(413.3275, 245.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4974)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9627)
layout:setPercentHeight(0.9408)
layout:setSize({width = 800.0000, height = 461.0000})
layout:setLeftMargin(13.3275)
layout:setRightMargin(17.6486)
layout:setTopMargin(14.5000)
layout:setBottomMargin(14.5000)
alert_view:addChild(Image_1)

--Create invitation_code_input_bg
local invitation_code_input_bg = ccui.ImageView:create()
invitation_code_input_bg:ignoreContentAdaptWithSize(false)
invitation_code_input_bg:loadTexture("hall_res/account/bb_grxx_bdzh_ditiao.png",0)
invitation_code_input_bg:setLayoutComponentEnabled(true)
invitation_code_input_bg:setName("invitation_code_input_bg")
invitation_code_input_bg:setTag(296)
invitation_code_input_bg:setCascadeColorEnabled(true)
invitation_code_input_bg:setCascadeOpacityEnabled(true)
invitation_code_input_bg:setPosition(415.4880, 294.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(invitation_code_input_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6000)
layout:setPercentWidth(0.5849)
layout:setPercentHeight(0.1082)
layout:setSize({width = 486.0000, height = 53.0000})
layout:setLeftMargin(172.4880)
layout:setRightMargin(172.4880)
layout:setTopMargin(169.5000)
layout:setBottomMargin(267.5000)
alert_view:addChild(invitation_code_input_bg)

--Create Text_4
local Text_4 = ccui.Text:create()
Text_4:ignoreContentAdaptWithSize(true)
Text_4:setTextAreaSize({width = 0, height = 0})
Text_4:setFontSize(30)
Text_4:setString([[请填写正确的邀请码以注册进入游戏]])
Text_4:setTextHorizontalAlignment(1)
Text_4:setTextVerticalAlignment(1)
Text_4:setLayoutComponentEnabled(true)
Text_4:setName("Text_4")
Text_4:setTag(297)
Text_4:setCascadeColorEnabled(true)
Text_4:setCascadeOpacityEnabled(true)
Text_4:setPosition(415.4880, 227.0000)
Text_4:setTextColor({r = 255, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4633)
layout:setPercentWidth(0.5776)
layout:setPercentHeight(0.0612)
layout:setSize({width = 480.0000, height = 30.0000})
layout:setLeftMargin(175.4880)
layout:setRightMargin(175.4880)
layout:setTopMargin(248.0000)
layout:setBottomMargin(212.0000)
alert_view:addChild(Text_4)

--Create Text_4_0
local Text_4_0 = ccui.Text:create()
Text_4_0:ignoreContentAdaptWithSize(true)
Text_4_0:setTextAreaSize({width = 0, height = 0})
Text_4_0:setFontSize(30)
Text_4_0:setString([[邀请码可以联系代理商获取]])
Text_4_0:setTextHorizontalAlignment(1)
Text_4_0:setTextVerticalAlignment(1)
Text_4_0:setLayoutComponentEnabled(true)
Text_4_0:setName("Text_4_0")
Text_4_0:setTag(299)
Text_4_0:setCascadeColorEnabled(true)
Text_4_0:setCascadeOpacityEnabled(true)
Text_4_0:setPosition(415.4880, 185.0000)
Text_4_0:setTextColor({r = 255, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4_0)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3776)
layout:setPercentWidth(0.4332)
layout:setPercentHeight(0.0612)
layout:setSize({width = 360.0000, height = 30.0000})
layout:setLeftMargin(235.4880)
layout:setRightMargin(235.4880)
layout:setTopMargin(290.0000)
layout:setBottomMargin(170.0000)
alert_view:addChild(Text_4_0)

--Create btn_sure
local btn_sure = ccui.Button:create()
btn_sure:ignoreContentAdaptWithSize(false)
btn_sure:loadTextureNormal("hall_res/account/bb_grxx_queren.png",0)
btn_sure:loadTexturePressed("hall_res/account/bb_grxx_queren1.png",0)
btn_sure:loadTextureDisabled("hall_res/account/bb_grxx_queren.png",0)
btn_sure:setTitleFontSize(14)
btn_sure:setTitleColor({r = 65, g = 65, b = 70})
btn_sure:setScale9Enabled(true)
btn_sure:setCapInsets({x = 15, y = 11, width = 257, height = 78})
btn_sure:setLayoutComponentEnabled(true)
btn_sure:setName("btn_sure")
btn_sure:setTag(300)
btn_sure:setCascadeColorEnabled(true)
btn_sure:setCascadeOpacityEnabled(true)
btn_sure:setPosition(415.4880, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_sure)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2041)
layout:setPercentWidth(0.3454)
layout:setPercentHeight(0.2041)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(271.9880)
layout:setRightMargin(271.9880)
layout:setTopMargin(340.0000)
layout:setBottomMargin(50.0000)
alert_view:addChild(btn_sure)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("hall_res/inviter/baobo_qsrndyqm.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(63)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(415.4880, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7347)
layout:setPercentWidth(0.3815)
layout:setPercentHeight(0.0776)
layout:setSize({width = 317.0000, height = 38.0000})
layout:setLeftMargin(256.9880)
layout:setRightMargin(256.9880)
layout:setTopMargin(111.0000)
layout:setBottomMargin(341.0000)
alert_view:addChild(Image_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

