--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.Layout:create()
bg:ignoreContentAdaptWithSize(false)
bg:setClippingEnabled(false)
bg:setBackGroundColorType(1)
bg:setBackGroundColor({r = 0, g = 0, b = 0})
bg:setBackGroundColorOpacity(102)
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(325)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg)

--Create background
local background = ccui.ImageView:create()
background:ignoreContentAdaptWithSize(false)
background:loadTexture("hall_res/tongyong/bb_ty_tc.png",0)
background:setScale9Enabled(true)
background:setCapInsets({x = 183, y = 118, width = 659, height = 474})
background:setLayoutComponentEnabled(true)
background:setName("background")
background:setTag(320)
background:setCascadeColorEnabled(true)
background:setCascadeOpacityEnabled(true)
background:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(background)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8008)
layout:setPercentHeight(0.8806)
layout:setSize({width = 1025.0000, height = 634.0000})
layout:setLeftMargin(127.5000)
layout:setRightMargin(127.5000)
layout:setTopMargin(43.0000)
layout:setBottomMargin(43.0000)
Layer:addChild(background)

--Create label_tip
local label_tip = ccui.Text:create()
label_tip:ignoreContentAdaptWithSize(false)
label_tip:setFontSize(30)
label_tip:setString([[哈哈]])
label_tip:setTextHorizontalAlignment(1)
label_tip:setTextVerticalAlignment(1)
label_tip:setLayoutComponentEnabled(true)
label_tip:setName("label_tip")
label_tip:setTag(51)
label_tip:setCascadeColorEnabled(true)
label_tip:setCascadeOpacityEnabled(true)
label_tip:setAnchorPoint(0.0000, 1.0000)
label_tip:setPosition(68.0000, 509.4211)
layout = ccui.LayoutComponent:bindLayoutComponent(label_tip)
layout:setPositionPercentX(0.0663)
layout:setPositionPercentY(0.8035)
layout:setPercentWidth(0.8780)
layout:setPercentHeight(0.4101)
layout:setSize({width = 900.0000, height = 260.0000})
layout:setLeftMargin(68.0000)
layout:setRightMargin(57.0000)
layout:setTopMargin(124.5789)
layout:setBottomMargin(249.4211)
background:addChild(label_tip)

--Create btn_service
local btn_service = ccui.Button:create()
btn_service:ignoreContentAdaptWithSize(false)
btn_service:loadTextureNormal("Default/Button_Normal.png",0)
btn_service:loadTexturePressed("Default/Button_Press.png",0)
btn_service:loadTextureDisabled("Default/Button_Disable.png",0)
btn_service:setTitleFontSize(14)
btn_service:setTitleColor({r = 65, g = 65, b = 70})
btn_service:setScale9Enabled(true)
btn_service:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn_service:setTouchEnabled(false);
btn_service:setLayoutComponentEnabled(true)
btn_service:setName("btn_service")
btn_service:setTag(323)
btn_service:setCascadeColorEnabled(true)
btn_service:setCascadeOpacityEnabled(true)
btn_service:setVisible(false)
btn_service:setPosition(512.5000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_service)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1577)
layout:setPercentWidth(0.3268)
layout:setPercentHeight(0.2382)
layout:setSize({width = 335.0000, height = 151.0000})
layout:setLeftMargin(345.0000)
layout:setRightMargin(345.0000)
layout:setTopMargin(458.5000)
layout:setBottomMargin(24.5000)
background:addChild(btn_service)

--Create btn_confirm
local btn_confirm = ccui.Button:create()
btn_confirm:ignoreContentAdaptWithSize(false)
btn_confirm:loadTextureNormal("hall_res/tongyong/bb_grxx_queren.png",0)
btn_confirm:loadTexturePressed("hall_res/tongyong/bb_grxx_queren1.png",0)
btn_confirm:loadTextureDisabled("hall_res/tongyong/bb_grxx_queren1.png",0)
btn_confirm:setTitleFontSize(14)
btn_confirm:setTitleColor({r = 65, g = 65, b = 70})
btn_confirm:setScale9Enabled(true)
btn_confirm:setCapInsets({x = 15, y = 11, width = 257, height = 78})
btn_confirm:setLayoutComponentEnabled(true)
btn_confirm:setName("btn_confirm")
btn_confirm:setTag(324)
btn_confirm:setCascadeColorEnabled(true)
btn_confirm:setCascadeOpacityEnabled(true)
btn_confirm:setPosition(512.5000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_confirm)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1577)
layout:setPercentWidth(0.2800)
layout:setPercentHeight(0.1577)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(369.0000)
layout:setRightMargin(369.0000)
layout:setTopMargin(484.0000)
layout:setBottomMargin(50.0000)
background:addChild(btn_confirm)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("hall_res/tongyong/bb_ty_gb.png",0)
btn_close:loadTexturePressed("hall_res/tongyong/bb_ty_gb1.png",0)
btn_close:loadTextureDisabled("hall_res/tongyong/bb_ty_gb1.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 37, height = 46})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(321)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(989.1892, 580.8658)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9651)
layout:setPositionPercentY(0.9162)
layout:setPercentWidth(0.0654)
layout:setPercentHeight(0.1073)
layout:setSize({width = 67.0000, height = 68.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(955.6892)
layout:setRightMargin(2.3108)
layout:setTopMargin(19.1342)
layout:setBottomMargin(546.8658)
background:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

