--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create tip_panel
local tip_panel = ccui.Layout:create()
tip_panel:ignoreContentAdaptWithSize(false)
tip_panel:setClippingEnabled(false)
tip_panel:setBackGroundColorOpacity(102)
tip_panel:setTouchEnabled(true);
tip_panel:setLayoutComponentEnabled(true)
tip_panel:setName("tip_panel")
tip_panel:setTag(29)
tip_panel:setCascadeColorEnabled(true)
tip_panel:setCascadeOpacityEnabled(true)
tip_panel:setAnchorPoint(0.5000, 0.0000)
tip_panel:setPosition(640.0000, -108.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.1500)
layout:setPercentWidth(0.6391)
layout:setPercentHeight(0.0862)
layout:setSize({width = 818.0000, height = 62.0584})
layout:setLeftMargin(231.0000)
layout:setRightMargin(231.0000)
layout:setTopMargin(765.9416)
layout:setBottomMargin(-108.0000)
Scene:addChild(tip_panel)

--Create Image_6
local Image_6 = ccui.ImageView:create()
Image_6:ignoreContentAdaptWithSize(false)
Image_6:loadTexture("hall_res/hall/bb_tubiao_gd_dk.png",0)
Image_6:setLayoutComponentEnabled(true)
Image_6:setName("Image_6")
Image_6:setTag(28)
Image_6:setCascadeColorEnabled(true)
Image_6:setCascadeOpacityEnabled(true)
Image_6:setAnchorPoint(0.5000, 1.0000)
Image_6:setPosition(409.0000, 78.1700)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_6)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.2596)
layout:setPercentWidth(0.6381)
layout:setPercentHeight(1.4341)
layout:setSize({width = 522.0000, height = 89.0000})
layout:setLeftMargin(148.0000)
layout:setRightMargin(148.0000)
layout:setTopMargin(-16.1116)
layout:setBottomMargin(-10.8300)
tip_panel:addChild(Image_6)

--Create tip_text
local tip_text = ccui.Text:create()
tip_text:ignoreContentAdaptWithSize(false)
tip_text:setFontSize(27)
tip_text:setString([[这是提示文字的占位符]])
tip_text:setTextHorizontalAlignment(1)
tip_text:setTextVerticalAlignment(1)
tip_text:setLayoutComponentEnabled(true)
tip_text:setName("tip_text")
tip_text:setTag(35)
tip_text:setCascadeColorEnabled(true)
tip_text:setCascadeOpacityEnabled(true)
tip_text:setPosition(409.0000, 25.5561)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4118)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(0.7335)
layout:setPercentHeight(1.0706)
layout:setSize({width = 600.0000, height = 66.4370})
layout:setLeftMargin(109.0000)
layout:setRightMargin(109.0000)
layout:setTopMargin(3.2838)
layout:setBottomMargin(-7.6624)
tip_panel:addChild(tip_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

