--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_4
local Panel_4 = ccui.Layout:create()
Panel_4:ignoreContentAdaptWithSize(false)
Panel_4:setBackGroundImage("hall_res/tongyong/bb_ty_di.jpg",0)
Panel_4:setClippingEnabled(false)
Panel_4:setBackGroundColorType(1)
Panel_4:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_4:setBackGroundColorOpacity(102)
Panel_4:setTouchEnabled(true);
Panel_4:setLayoutComponentEnabled(true)
Panel_4:setName("Panel_4")
Panel_4:setTag(115)
Panel_4:setCascadeColorEnabled(true)
Panel_4:setCascadeOpacityEnabled(true)
Panel_4:setAnchorPoint(0.5000, 0.5000)
Panel_4:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_4)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_4)

--Create FileNode_1
innerCSD = require("PublicTopInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(58)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(0.0000, 720.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(1.0000)
layout:setRightMargin(1280.0000)
layout:setBottomMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Panel_4:addChild(FileNode_1)

--Create Image_51
local Image_51 = ccui.ImageView:create()
Image_51:ignoreContentAdaptWithSize(false)
Image_51:loadTexture("hall_res/tongyong/bb_ty_zuodi.png",0)
Image_51:setLayoutComponentEnabled(true)
Image_51:setName("Image_51")
Image_51:setTag(351)
Image_51:setCascadeColorEnabled(true)
Image_51:setCascadeOpacityEnabled(true)
Image_51:setAnchorPoint(0.0000, 0.5000)
Image_51:setPosition(0.0000, 312.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_51)
layout:setPositionPercentY(0.4333)
layout:setPercentWidth(0.2047)
layout:setPercentHeight(0.8861)
layout:setSize({width = 262.0000, height = 638.0000})
layout:setRightMargin(1018.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(-7.0000)
Panel_4:addChild(Image_51)

--Create btns_parent_view
local btns_parent_view = ccui.Layout:create()
btns_parent_view:ignoreContentAdaptWithSize(false)
btns_parent_view:setClippingEnabled(false)
btns_parent_view:setBackGroundColorOpacity(102)
btns_parent_view:setTouchEnabled(true);
btns_parent_view:setLayoutComponentEnabled(true)
btns_parent_view:setName("btns_parent_view")
btns_parent_view:setTag(76)
btns_parent_view:setCascadeColorEnabled(true)
btns_parent_view:setCascadeOpacityEnabled(true)
btns_parent_view:setAnchorPoint(0.0000, 1.0000)
btns_parent_view:setPosition(0.0000, 627.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(btns_parent_view)
layout:setPositionPercentY(0.8714)
layout:setPercentWidth(0.2148)
layout:setPercentHeight(0.7097)
layout:setSize({width = 275.0000, height = 511.0000})
layout:setRightMargin(1005.0000)
layout:setTopMargin(92.6000)
layout:setBottomMargin(116.4000)
Panel_4:addChild(btns_parent_view)

--Create account_bind_view_btn
local account_bind_view_btn = ccui.Button:create()
account_bind_view_btn:ignoreContentAdaptWithSize(false)
account_bind_view_btn:loadTextureNormal("hall_res/account/bb_grxx_bangdingzhanghao1.png",0)
account_bind_view_btn:loadTexturePressed("hall_res/account/bb_grxx_bangdingzhanghao.png",0)
account_bind_view_btn:loadTextureDisabled("hall_res/account/bb_grxx_bangdingzhanghao.png",0)
account_bind_view_btn:setTitleFontSize(14)
account_bind_view_btn:setTitleColor({r = 65, g = 65, b = 70})
account_bind_view_btn:setScale9Enabled(true)
account_bind_view_btn:setCapInsets({x = 15, y = 11, width = 240, height = 58})
account_bind_view_btn:setBright(false)
account_bind_view_btn:setLayoutComponentEnabled(true)
account_bind_view_btn:setName("account_bind_view_btn")
account_bind_view_btn:setLocalZOrder(3)
account_bind_view_btn:setTag(77)
account_bind_view_btn:setCascadeColorEnabled(true)
account_bind_view_btn:setCascadeOpacityEnabled(true)
account_bind_view_btn:setAnchorPoint(0.0000, 0.5000)
account_bind_view_btn:setPosition(0.0000, 429.1160)
layout = ccui.LayoutComponent:bindLayoutComponent(account_bind_view_btn)
layout:setPositionPercentY(0.8398)
layout:setPercentWidth(0.9818)
layout:setPercentHeight(0.1566)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(5.0000)
layout:setTopMargin(41.8840)
layout:setBottomMargin(389.1160)
btns_parent_view:addChild(account_bind_view_btn)

--Create person_info_view_btn
local person_info_view_btn = ccui.Button:create()
person_info_view_btn:ignoreContentAdaptWithSize(false)
person_info_view_btn:loadTextureNormal("hall_res/account/bb_grxx_gerenxinxi1.png",0)
person_info_view_btn:loadTexturePressed("hall_res/account/bb_grxx_gerenxinxi.png",0)
person_info_view_btn:loadTextureDisabled("hall_res/account/bb_grxx_gerenxinxi.png",0)
person_info_view_btn:setTitleFontSize(14)
person_info_view_btn:setTitleColor({r = 65, g = 65, b = 70})
person_info_view_btn:setScale9Enabled(true)
person_info_view_btn:setCapInsets({x = 15, y = 11, width = 240, height = 58})
person_info_view_btn:setLayoutComponentEnabled(true)
person_info_view_btn:setName("person_info_view_btn")
person_info_view_btn:setLocalZOrder(3)
person_info_view_btn:setTag(79)
person_info_view_btn:setCascadeColorEnabled(true)
person_info_view_btn:setCascadeOpacityEnabled(true)
person_info_view_btn:setAnchorPoint(0.0000, 0.5000)
person_info_view_btn:setPosition(0.0000, 345.3279)
layout = ccui.LayoutComponent:bindLayoutComponent(person_info_view_btn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentY(0.6758)
layout:setPercentWidth(0.9818)
layout:setPercentHeight(0.1566)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(5.0000)
layout:setTopMargin(125.6721)
layout:setBottomMargin(305.3279)
btns_parent_view:addChild(person_info_view_btn)

--Create sub_view_parent
local sub_view_parent = ccui.Layout:create()
sub_view_parent:ignoreContentAdaptWithSize(false)
sub_view_parent:setClippingEnabled(false)
sub_view_parent:setBackGroundColorOpacity(102)
sub_view_parent:setTouchEnabled(true);
sub_view_parent:setLayoutComponentEnabled(true)
sub_view_parent:setName("sub_view_parent")
sub_view_parent:setTag(264)
sub_view_parent:setCascadeColorEnabled(true)
sub_view_parent:setCascadeOpacityEnabled(true)
sub_view_parent:setAnchorPoint(0.0000, 1.0000)
sub_view_parent:setPosition(355.5337, 628.7684)
layout = ccui.LayoutComponent:bindLayoutComponent(sub_view_parent)
layout:setPositionPercentX(0.2778)
layout:setPositionPercentY(0.8733)
layout:setPercentWidth(0.7172)
layout:setPercentHeight(0.8611)
layout:setSize({width = 918.0000, height = 620.0000})
layout:setLeftMargin(355.5337)
layout:setRightMargin(6.4663)
layout:setTopMargin(91.2316)
layout:setBottomMargin(8.7684)
Panel_4:addChild(sub_view_parent)

--Create FileNode_1
innerCSD = require("AlipayBindInfoLayerCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(265)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(0.0000, -0.1395)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentY(-0.0002)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 918.0000, height = 620.0000})
layout:setTopMargin(0.1395)
layout:setBottomMargin(-0.1395)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
sub_view_parent:addChild(FileNode_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

