--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("hall_res/tongyong/bb_ty_di.jpg",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(561)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setAnchorPoint(0.0000, 0.0000)
Image_2:setPosition(0.0000, -720.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setRightMargin(-1280.0000)
layout:setBottomMargin(-720.0000)
Node:addChild(Image_2)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(284)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(0.0000, -84.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 1280.0000, height = 84.0000})
layout:setRightMargin(-1280.0000)
layout:setBottomMargin(-84.0000)
Node:addChild(Panel_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("hall_res/tongyong/bb_ty_shang.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(285)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.5000, 0.0000)
Image_1:setPosition(640.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 84.0000})
Panel_1:addChild(Image_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("hall_res/hall/bb_dating_gerenxinxi.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(374)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(186.0000, 59.6144)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.1453)
layout:setPositionPercentY(0.7097)
layout:setPercentWidth(0.1352)
layout:setPercentHeight(0.3810)
layout:setSize({width = 173.0000, height = 32.0000})
layout:setLeftMargin(99.5000)
layout:setRightMargin(1007.5000)
layout:setTopMargin(8.3856)
layout:setBottomMargin(43.6144)
Panel_1:addChild(Image_1)

--Create nickname_text
local nickname_text = ccui.Text:create()
nickname_text:ignoreContentAdaptWithSize(true)
nickname_text:setTextAreaSize({width = 0, height = 0})
nickname_text:setFontSize(24)
nickname_text:setString([[名字昵称7个字]])
nickname_text:enableShadow({r = 255, g = 255, b = 255, a = 255}, {width = 0, height = 0}, 0)
nickname_text:setLayoutComponentEnabled(true)
nickname_text:setName("nickname_text")
nickname_text:setTag(375)
nickname_text:setCascadeColorEnabled(true)
nickname_text:setCascadeOpacityEnabled(true)
nickname_text:setAnchorPoint(0.0000, 0.5000)
nickname_text:setPosition(10.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nickname_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0578)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9017)
layout:setPercentHeight(0.7500)
layout:setSize({width = 156.0000, height = 24.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(7.0000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
Image_1:addChild(nickname_text)

--Create Image_2_0
local Image_2_0 = ccui.ImageView:create()
Image_2_0:ignoreContentAdaptWithSize(false)
Image_2_0:loadTexture("hall_res/hall/bb_dating_gerenxinxi.png",0)
Image_2_0:setLayoutComponentEnabled(true)
Image_2_0:setName("Image_2_0")
Image_2_0:setTag(372)
Image_2_0:setCascadeColorEnabled(true)
Image_2_0:setCascadeOpacityEnabled(true)
Image_2_0:setPosition(188.0100, 25.9857)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2_0)
layout:setPositionPercentX(0.1469)
layout:setPositionPercentY(0.3094)
layout:setPercentWidth(0.1352)
layout:setPercentHeight(0.3810)
layout:setSize({width = 173.0000, height = 32.0000})
layout:setLeftMargin(101.5100)
layout:setRightMargin(1005.4900)
layout:setTopMargin(42.0143)
layout:setBottomMargin(9.9857)
Panel_1:addChild(Image_2_0)

--Create player_id_text
local player_id_text = ccui.Text:create()
player_id_text:ignoreContentAdaptWithSize(true)
player_id_text:setTextAreaSize({width = 0, height = 0})
player_id_text:setFontSize(24)
player_id_text:setString([[ID:9527]])
player_id_text:enableShadow({r = 255, g = 206, b = 119, a = 255}, {width = 0, height = 0}, 0)
player_id_text:setLayoutComponentEnabled(true)
player_id_text:setName("player_id_text")
player_id_text:setTag(373)
player_id_text:setCascadeColorEnabled(true)
player_id_text:setCascadeOpacityEnabled(true)
player_id_text:setAnchorPoint(0.0000, 0.5000)
player_id_text:setPosition(10.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(player_id_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0578)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4855)
layout:setPercentHeight(0.7500)
layout:setSize({width = 84.0000, height = 24.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(79.0000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
Image_2_0:addChild(player_id_text)

--Create gold_bg
local gold_bg = ccui.ImageView:create()
gold_bg:ignoreContentAdaptWithSize(false)
gold_bg:loadTexture("hall_res/hall/bb_dating_choumashuru.png",0)
gold_bg:setLayoutComponentEnabled(true)
gold_bg:setName("gold_bg")
gold_bg:setTag(289)
gold_bg:setCascadeColorEnabled(true)
gold_bg:setCascadeOpacityEnabled(true)
gold_bg:setPosition(425.0204, 42.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gold_bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3320)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1758)
layout:setPercentHeight(0.7143)
layout:setSize({width = 225.0000, height = 60.0000})
layout:setLeftMargin(312.5204)
layout:setRightMargin(742.4796)
layout:setTopMargin(12.0000)
layout:setBottomMargin(12.0000)
Panel_1:addChild(gold_bg)

--Create add_gold_btn1
local add_gold_btn1 = ccui.Button:create()
add_gold_btn1:ignoreContentAdaptWithSize(false)
add_gold_btn1:loadTextureNormal("hall_res/hall/bb_dating_jiahao_normal.png",0)
add_gold_btn1:loadTexturePressed("hall_res/hall/bb_dating_jiahao_pressed.png",0)
add_gold_btn1:loadTextureDisabled("hall_res/hall/bb_dating_jiahao_pressed.png",0)
add_gold_btn1:setTitleFontSize(14)
add_gold_btn1:setTitleColor({r = 65, g = 65, b = 70})
add_gold_btn1:setScale9Enabled(true)
add_gold_btn1:setCapInsets({x = 15, y = 11, width = 22, height = 31})
add_gold_btn1:setLayoutComponentEnabled(true)
add_gold_btn1:setName("add_gold_btn1")
add_gold_btn1:setTag(290)
add_gold_btn1:setCascadeColorEnabled(true)
add_gold_btn1:setCascadeOpacityEnabled(true)
add_gold_btn1:setPosition(243.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(add_gold_btn1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(1.0800)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2311)
layout:setPercentHeight(0.8833)
layout:setSize({width = 52.0000, height = 53.0000})
layout:setLeftMargin(217.0000)
layout:setRightMargin(-44.0000)
layout:setTopMargin(3.5000)
layout:setBottomMargin(3.5000)
gold_bg:addChild(add_gold_btn1)

--Create top_gold_text
local top_gold_text = ccui.TextAtlas:create([[9990922]],
													"hall_res/hall/bb_tubiao_shuzi.png",
													16,
													24,
													"/")
top_gold_text:setLayoutComponentEnabled(true)
top_gold_text:setName("top_gold_text")
top_gold_text:setTag(353)
top_gold_text:setCascadeColorEnabled(true)
top_gold_text:setCascadeOpacityEnabled(true)
top_gold_text:setPosition(132.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(top_gold_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5867)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4978)
layout:setPercentHeight(0.4000)
layout:setSize({width = 112.0000, height = 24.0000})
layout:setLeftMargin(76.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(18.0000)
layout:setBottomMargin(18.0000)
gold_bg:addChild(top_gold_text)

--Create bank_bg
local bank_bg = ccui.ImageView:create()
bank_bg:ignoreContentAdaptWithSize(false)
bank_bg:loadTexture("hall_res/hall/bb_dating_yinghangshuru.png",0)
bank_bg:setLayoutComponentEnabled(true)
bank_bg:setName("bank_bg")
bank_bg:setTag(351)
bank_bg:setCascadeColorEnabled(true)
bank_bg:setCascadeOpacityEnabled(true)
bank_bg:setPosition(730.6910, 42.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bank_bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5709)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1758)
layout:setPercentHeight(0.7143)
layout:setSize({width = 225.0000, height = 60.0000})
layout:setLeftMargin(618.1910)
layout:setRightMargin(436.8090)
layout:setTopMargin(12.0000)
layout:setBottomMargin(12.0000)
Panel_1:addChild(bank_bg)

--Create top_bank_text
local top_bank_text = ccui.TextAtlas:create([[9990922]],
													"hall_res/hall/bb_tubiao_shuzi.png",
													16,
													24,
													"/")
top_bank_text:setLayoutComponentEnabled(true)
top_bank_text:setName("top_bank_text")
top_bank_text:setTag(354)
top_bank_text:setCascadeColorEnabled(true)
top_bank_text:setCascadeOpacityEnabled(true)
top_bank_text:setPosition(132.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(top_bank_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5867)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4978)
layout:setPercentHeight(0.4000)
layout:setSize({width = 112.0000, height = 24.0000})
layout:setLeftMargin(76.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(18.0000)
layout:setBottomMargin(18.0000)
bank_bg:addChild(top_bank_text)

--Create add_gold_btn2
local add_gold_btn2 = ccui.Button:create()
add_gold_btn2:ignoreContentAdaptWithSize(false)
add_gold_btn2:loadTextureNormal("hall_res/hall/bb_dating_jiahao_normal.png",0)
add_gold_btn2:loadTexturePressed("hall_res/hall/bb_dating_jiahao_pressed.png",0)
add_gold_btn2:loadTextureDisabled("hall_res/hall/bb_dating_jiahao_pressed.png",0)
add_gold_btn2:setTitleFontSize(14)
add_gold_btn2:setTitleColor({r = 65, g = 65, b = 70})
add_gold_btn2:setScale9Enabled(true)
add_gold_btn2:setCapInsets({x = 15, y = 11, width = 22, height = 31})
add_gold_btn2:setLayoutComponentEnabled(true)
add_gold_btn2:setName("add_gold_btn2")
add_gold_btn2:setTag(352)
add_gold_btn2:setCascadeColorEnabled(true)
add_gold_btn2:setCascadeOpacityEnabled(true)
add_gold_btn2:setPosition(243.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(add_gold_btn2)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(1.0800)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2311)
layout:setPercentHeight(0.8833)
layout:setSize({width = 52.0000, height = 53.0000})
layout:setLeftMargin(217.0000)
layout:setRightMargin(-44.0000)
layout:setTopMargin(3.5000)
layout:setBottomMargin(3.5000)
bank_bg:addChild(add_gold_btn2)

--Create titile_view
local titile_view = ccui.ImageView:create()
titile_view:ignoreContentAdaptWithSize(false)
titile_view:loadTexture("hall_res/bank_new/bb_cmdh_yh_bt.png",0)
titile_view:setLayoutComponentEnabled(true)
titile_view:setName("titile_view")
titile_view:setTag(288)
titile_view:setCascadeColorEnabled(true)
titile_view:setCascadeOpacityEnabled(true)
titile_view:setAnchorPoint(1.0000, 0.5000)
titile_view:setPosition(1280.0000, 22.5470)
layout = ccui.LayoutComponent:bindLayoutComponent(titile_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.2684)
layout:setPercentWidth(0.2727)
layout:setPercentHeight(1.4167)
layout:setSize({width = 349.0000, height = 119.0000})
layout:setLeftMargin(931.0000)
layout:setTopMargin(1.9530)
layout:setBottomMargin(-36.9530)
Panel_1:addChild(titile_view)

--Create close_btn
local close_btn = ccui.Button:create()
close_btn:ignoreContentAdaptWithSize(false)
close_btn:loadTextureNormal("hall_res/tongyong/bb_ty_fh.png",0)
close_btn:loadTexturePressed("hall_res/tongyong/bb_ty_fh1.png",0)
close_btn:loadTextureDisabled("hall_res/tongyong/bb_ty_fh1.png",0)
close_btn:setTitleFontSize(14)
close_btn:setTitleColor({r = 65, g = 65, b = 70})
close_btn:setScale9Enabled(true)
close_btn:setCapInsets({x = 15, y = 11, width = 35, height = 38})
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setTag(287)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setPosition(44.5000, 42.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0348)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0508)
layout:setPercentHeight(0.7143)
layout:setSize({width = 65.0000, height = 60.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(1203.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(12.0000)
Panel_1:addChild(close_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

