--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(126)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(179)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create alert_panel
local alert_panel = ccui.Layout:create()
alert_panel:ignoreContentAdaptWithSize(false)
alert_panel:setBackGroundImage("hall_res/account/bb_xgmm_d.png",0)
alert_panel:setClippingEnabled(false)
alert_panel:setBackGroundColorOpacity(102)
alert_panel:setTouchEnabled(true);
alert_panel:setLayoutComponentEnabled(true)
alert_panel:setName("alert_panel")
alert_panel:setTag(180)
alert_panel:setCascadeColorEnabled(true)
alert_panel:setCascadeOpacityEnabled(true)
alert_panel:setAnchorPoint(0.5000, 0.5000)
alert_panel:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alert_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Panel_1:addChild(alert_panel)

--Create close_btn
local close_btn = ccui.Button:create()
close_btn:ignoreContentAdaptWithSize(false)
close_btn:loadTextureNormal("Default/Button_Normal.png",0)
close_btn:loadTexturePressed("Default/Button_Press.png",0)
close_btn:loadTextureDisabled("Default/Button_Disable.png",0)
close_btn:setTitleFontSize(14)
close_btn:setTitleColor({r = 65, g = 65, b = 70})
close_btn:setScale9Enabled(true)
close_btn:setCapInsets({x = 15, y = 11, width = 63, height = 61})
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setTag(190)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setPosition(1183.9760, 630.0640)
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentX(0.9250)
layout:setPositionPercentY(0.8751)
layout:setPercentWidth(0.0508)
layout:setPercentHeight(0.0903)
layout:setSize({width = 65.0000, height = 65.0000})
layout:setLeftMargin(1151.4760)
layout:setRightMargin(63.5239)
layout:setTopMargin(57.4360)
layout:setBottomMargin(597.5640)
alert_panel:addChild(close_btn)

--Create text_1
local text_1 = ccui.Text:create()
text_1:ignoreContentAdaptWithSize(true)
text_1:setTextAreaSize({width = 0, height = 0})
text_1:setFontSize(30)
text_1:setString([[如果您对代理商有任何疑问和不满，请在下方输入你想反馈的内容]])
text_1:setLayoutComponentEnabled(true)
text_1:setName("text_1")
text_1:setTag(191)
text_1:setCascadeColorEnabled(true)
text_1:setCascadeOpacityEnabled(true)
text_1:setPosition(640.0000, 604.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8389)
layout:setPercentWidth(0.6797)
layout:setPercentHeight(0.0417)
layout:setSize({width = 870.0000, height = 30.0000})
layout:setLeftMargin(205.0000)
layout:setRightMargin(205.0000)
layout:setTopMargin(101.0000)
layout:setBottomMargin(589.0000)
alert_panel:addChild(text_1)

--Create Image_11
local Image_11 = ccui.ImageView:create()
Image_11:ignoreContentAdaptWithSize(false)
Image_11:loadTexture("Default/ImageFile.png",0)
Image_11:setLayoutComponentEnabled(true)
Image_11:setName("Image_11")
Image_11:setTag(192)
Image_11:setCascadeColorEnabled(true)
Image_11:setCascadeOpacityEnabled(true)
Image_11:setPosition(620.0000, 384.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_11)
layout:setPositionPercentX(0.4844)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.8008)
layout:setPercentHeight(0.3917)
layout:setSize({width = 1025.0000, height = 282.0000})
layout:setLeftMargin(107.5000)
layout:setRightMargin(147.5000)
layout:setTopMargin(195.0000)
layout:setBottomMargin(243.0000)
alert_panel:addChild(Image_11)

--Create text_2
local text_2 = ccui.Text:create()
text_2:ignoreContentAdaptWithSize(true)
text_2:setTextAreaSize({width = 0, height = 0})
text_2:setFontSize(30)
text_2:setString([[请注明你要反馈的内容]])
text_2:setLayoutComponentEnabled(true)
text_2:setName("text_2")
text_2:setTag(193)
text_2:setCascadeColorEnabled(true)
text_2:setCascadeOpacityEnabled(true)
text_2:setPosition(640.0000, 221.0000)
text_2:setTextColor({r = 175, g = 210, b = 216})
layout = ccui.LayoutComponent:bindLayoutComponent(text_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3069)
layout:setPercentWidth(0.2344)
layout:setPercentHeight(0.0417)
layout:setSize({width = 300.0000, height = 30.0000})
layout:setLeftMargin(490.0000)
layout:setRightMargin(490.0000)
layout:setTopMargin(484.0000)
layout:setBottomMargin(206.0000)
alert_panel:addChild(text_2)

--Create text_3
local text_3 = ccui.Text:create()
text_3:ignoreContentAdaptWithSize(true)
text_3:setTextAreaSize({width = 0, height = 0})
text_3:setFontSize(30)
text_3:setString([[你还可以通过QQ:4454544,或者微信:5245421联系]])
text_3:setLayoutComponentEnabled(true)
text_3:setName("text_3")
text_3:setTag(194)
text_3:setCascadeColorEnabled(true)
text_3:setCascadeOpacityEnabled(true)
text_3:setAnchorPoint(0.5031, 0.5667)
text_3:setPosition(640.0000, 184.0000)
text_3:setTextColor({r = 175, g = 210, b = 216})
layout = ccui.LayoutComponent:bindLayoutComponent(text_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2556)
layout:setPercentWidth(0.5039)
layout:setPercentHeight(0.0417)
layout:setSize({width = 645.0000, height = 30.0000})
layout:setLeftMargin(315.5005)
layout:setRightMargin(319.4995)
layout:setTopMargin(523.0010)
layout:setBottomMargin(166.9990)
alert_panel:addChild(text_3)

--Create submit_btn
local submit_btn = ccui.Button:create()
submit_btn:ignoreContentAdaptWithSize(false)
submit_btn:loadTextureNormal("Default/Button_Normal.png",0)
submit_btn:loadTexturePressed("Default/Button_Press.png",0)
submit_btn:loadTextureDisabled("Default/Button_Disable.png",0)
submit_btn:setTitleFontSize(14)
submit_btn:setTitleColor({r = 65, g = 65, b = 70})
submit_btn:setScale9Enabled(true)
submit_btn:setCapInsets({x = 15, y = 11, width = 305, height = 129})
submit_btn:setLayoutComponentEnabled(true)
submit_btn:setName("submit_btn")
submit_btn:setTag(196)
submit_btn:setCascadeColorEnabled(true)
submit_btn:setCascadeOpacityEnabled(true)
submit_btn:setPosition(640.0000, 104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(submit_btn)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1444)
layout:setPercentWidth(0.2617)
layout:setPercentHeight(0.2097)
layout:setSize({width = 335.0000, height = 151.0000})
layout:setLeftMargin(472.5000)
layout:setRightMargin(472.5000)
layout:setTopMargin(540.5000)
layout:setBottomMargin(28.5000)
alert_panel:addChild(submit_btn)

--Create content_textfiled
local content_textfiled = ccui.TextField:create()
content_textfiled:ignoreContentAdaptWithSize(false)
tolua.cast(content_textfiled:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
content_textfiled:setFontSize(20)
content_textfiled:setPlaceHolder("")
content_textfiled:setString([[]])
content_textfiled:setMaxLengthEnabled(true)
content_textfiled:setMaxLength(100)
content_textfiled:setLayoutComponentEnabled(true)
content_textfiled:setName("content_textfiled")
content_textfiled:setTag(195)
content_textfiled:setCascadeColorEnabled(true)
content_textfiled:setCascadeOpacityEnabled(true)
content_textfiled:setPosition(620.0000, 379.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(content_textfiled)
layout:setPositionPercentX(0.4844)
layout:setPositionPercentY(0.5264)
layout:setPercentWidth(0.7813)
layout:setPercentHeight(0.3889)
layout:setSize({width = 1000.0000, height = 280.0000})
layout:setLeftMargin(120.0000)
layout:setRightMargin(160.0000)
layout:setTopMargin(201.0000)
layout:setBottomMargin(239.0000)
alert_panel:addChild(content_textfiled)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

