--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 240.0000, height = 188.0000})

--Create game_panel
local game_panel = ccui.Layout:create()
game_panel:ignoreContentAdaptWithSize(false)
game_panel:setClippingEnabled(true)
game_panel:setBackGroundColorOpacity(102)
game_panel:setTouchEnabled(true);
game_panel:setLayoutComponentEnabled(true)
game_panel:setName("game_panel")
game_panel:setTag(409)
game_panel:setCascadeColorEnabled(true)
game_panel:setCascadeOpacityEnabled(true)
game_panel:setPosition(0.0001, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(game_panel)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 240.0000, height = 188.0000})
layout:setLeftMargin(0.0001)
layout:setRightMargin(-0.0001)
Layer:addChild(game_panel)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("hall_res/bank_new/dl_recharge/baobo_popupview_dikuang.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(410)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(120.0000, 94.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9125)
layout:setPercentHeight(0.8883)
layout:setSize({width = 219.0000, height = 167.0000})
layout:setLeftMargin(10.5000)
layout:setRightMargin(10.5000)
layout:setTopMargin(10.5000)
layout:setBottomMargin(10.5000)
game_panel:addChild(Image_3)

--Create btn_recharge
local btn_recharge = ccui.Button:create()
btn_recharge:ignoreContentAdaptWithSize(false)
btn_recharge:loadTextureNormal("hall_res/bank_new/dl_recharge/baobo_popupview_button_chongzhi.png",0)
btn_recharge:loadTexturePressed("hall_res/bank_new/dl_recharge/baobo_popupview_button_chongzhi1.png",0)
btn_recharge:loadTextureDisabled("hall_res/bank_new/dl_recharge/baobo_popupview_button_chongzhi1.png",0)
btn_recharge:setTitleFontSize(14)
btn_recharge:setTitleColor({r = 65, g = 65, b = 70})
btn_recharge:setScale9Enabled(true)
btn_recharge:setCapInsets({x = 15, y = 11, width = 170, height = 51})
btn_recharge:setLayoutComponentEnabled(true)
btn_recharge:setName("btn_recharge")
btn_recharge:setTag(411)
btn_recharge:setCascadeColorEnabled(true)
btn_recharge:setCascadeOpacityEnabled(true)
btn_recharge:setPosition(122.6625, 65.8200)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_recharge)
layout:setPositionPercentX(0.5111)
layout:setPositionPercentY(0.3501)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.3883)
layout:setSize({width = 200.0000, height = 73.0000})
layout:setLeftMargin(22.6625)
layout:setRightMargin(17.3375)
layout:setTopMargin(85.6800)
layout:setBottomMargin(29.3200)
game_panel:addChild(btn_recharge)

--Create text_name
local text_name = ccui.Text:create()
text_name:ignoreContentAdaptWithSize(true)
text_name:setTextAreaSize({width = 0, height = 0})
text_name:setFontSize(30)
text_name:setString([[代理商]])
text_name:setLayoutComponentEnabled(true)
text_name:setName("text_name")
text_name:setTag(412)
text_name:setCascadeColorEnabled(true)
text_name:setCascadeOpacityEnabled(true)
text_name:setPosition(122.6580, 146.8362)
layout = ccui.LayoutComponent:bindLayoutComponent(text_name)
layout:setPositionPercentX(0.5111)
layout:setPositionPercentY(0.7810)
layout:setPercentWidth(0.3750)
layout:setPercentHeight(0.1596)
layout:setSize({width = 90.0000, height = 30.0000})
layout:setLeftMargin(77.6580)
layout:setRightMargin(72.3420)
layout:setTopMargin(26.1638)
layout:setBottomMargin(131.8362)
game_panel:addChild(text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

