--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 950.0000, height = 615.0000})

--Create Panel_dlcz
local Panel_dlcz = ccui.Layout:create()
Panel_dlcz:ignoreContentAdaptWithSize(false)
Panel_dlcz:setClippingEnabled(true)
Panel_dlcz:setBackGroundColorOpacity(102)
Panel_dlcz:setTouchEnabled(true);
Panel_dlcz:setLayoutComponentEnabled(true)
Panel_dlcz:setName("Panel_dlcz")
Panel_dlcz:setTag(528)
Panel_dlcz:setCascadeColorEnabled(true)
Panel_dlcz:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_dlcz)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 950.0000, height = 615.0000})
Layer:addChild(Panel_dlcz)

--Create Panel_dls
local Panel_dls = ccui.Layout:create()
Panel_dls:ignoreContentAdaptWithSize(false)
Panel_dls:setClippingEnabled(false)
Panel_dls:setBackGroundColorOpacity(102)
Panel_dls:setTouchEnabled(true);
Panel_dls:setLayoutComponentEnabled(true)
Panel_dls:setName("Panel_dls")
Panel_dls:setTag(535)
Panel_dls:setCascadeColorEnabled(true)
Panel_dls:setCascadeOpacityEnabled(true)
Panel_dls:setPosition(1.8372, 198.7278)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_dls)
layout:setPositionPercentX(0.0019)
layout:setPositionPercentY(0.3231)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6732)
layout:setSize({width = 950.0000, height = 414.0000})
layout:setLeftMargin(1.8372)
layout:setRightMargin(-1.8373)
layout:setTopMargin(2.2722)
layout:setBottomMargin(198.7278)
Panel_dlcz:addChild(Panel_dls)

--Create btn_yhfk
local btn_yhfk = ccui.Button:create()
btn_yhfk:ignoreContentAdaptWithSize(false)
btn_yhfk:loadTextureNormal("hall_res/bank_new/dl_recharge/baobo_popupview_button_yhfk.png",0)
btn_yhfk:loadTexturePressed("hall_res/bank_new/dl_recharge/baobo_popupview_button_yhfk1.png",0)
btn_yhfk:loadTextureDisabled("hall_res/bank_new/dl_recharge/baobo_popupview_button_yhfk1.png",0)
btn_yhfk:setTitleFontSize(14)
btn_yhfk:setTitleColor({r = 65, g = 65, b = 70})
btn_yhfk:setScale9Enabled(true)
btn_yhfk:setCapInsets({x = 15, y = 11, width = 257, height = 78})
btn_yhfk:setLayoutComponentEnabled(true)
btn_yhfk:setName("btn_yhfk")
btn_yhfk:setTag(537)
btn_yhfk:setCascadeColorEnabled(true)
btn_yhfk:setCascadeOpacityEnabled(true)
btn_yhfk:setPosition(475.2823, 58.8744)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_yhfk)
layout:setPositionPercentX(0.5003)
layout:setPositionPercentY(0.0957)
layout:setPercentWidth(0.3021)
layout:setPercentHeight(0.1626)
layout:setSize({width = 287.0000, height = 100.0000})
layout:setLeftMargin(331.7823)
layout:setRightMargin(331.2177)
layout:setTopMargin(506.1256)
layout:setBottomMargin(8.8744)
Panel_dlcz:addChild(btn_yhfk)

--Create btn_left
local btn_left = ccui.Button:create()
btn_left:ignoreContentAdaptWithSize(false)
btn_left:loadTextureNormal("hall_res/flip_button/baobo_an_left_normal.png",0)
btn_left:loadTexturePressed("hall_res/flip_button/baobo_an_left_pressed.png",0)
btn_left:loadTextureDisabled("hall_res/flip_button/baobo_an_left_pressed.png",0)
btn_left:setTitleFontSize(14)
btn_left:setTitleColor({r = 65, g = 65, b = 70})
btn_left:setScale9Enabled(true)
btn_left:setCapInsets({x = 15, y = 11, width = 25, height = 46})
btn_left:setLayoutComponentEnabled(true)
btn_left:setName("btn_left")
btn_left:setTag(538)
btn_left:setCascadeColorEnabled(true)
btn_left:setCascadeOpacityEnabled(true)
btn_left:setPosition(237.2904, 58.8744)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_left)
layout:setPositionPercentX(0.2498)
layout:setPositionPercentY(0.0957)
layout:setPercentWidth(0.0579)
layout:setPercentHeight(0.1106)
layout:setSize({width = 55.0000, height = 68.0000})
layout:setLeftMargin(209.7904)
layout:setRightMargin(685.2096)
layout:setTopMargin(522.1256)
layout:setBottomMargin(24.8744)
Panel_dlcz:addChild(btn_left)

--Create btn_right
local btn_right = ccui.Button:create()
btn_right:ignoreContentAdaptWithSize(false)
btn_right:loadTextureNormal("hall_res/flip_button/baobo_an_right_normal.png",0)
btn_right:loadTexturePressed("hall_res/flip_button/baobo_an_right_pressed.png",0)
btn_right:loadTextureDisabled("hall_res/flip_button/baobo_an_right_pressed.png",0)
btn_right:setTitleFontSize(14)
btn_right:setTitleColor({r = 65, g = 65, b = 70})
btn_right:setScale9Enabled(true)
btn_right:setCapInsets({x = 15, y = 11, width = 25, height = 46})
btn_right:setLayoutComponentEnabled(true)
btn_right:setName("btn_right")
btn_right:setTag(539)
btn_right:setCascadeColorEnabled(true)
btn_right:setCascadeOpacityEnabled(true)
btn_right:setPosition(713.2766, 58.8744)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_right)
layout:setPositionPercentX(0.7508)
layout:setPositionPercentY(0.0957)
layout:setPercentWidth(0.0579)
layout:setPercentHeight(0.1106)
layout:setSize({width = 55.0000, height = 68.0000})
layout:setLeftMargin(685.7766)
layout:setRightMargin(209.2234)
layout:setTopMargin(522.1256)
layout:setBottomMargin(24.8744)
Panel_dlcz:addChild(btn_right)

--Create Text_26
local Text_26 = ccui.Text:create()
Text_26:ignoreContentAdaptWithSize(true)
Text_26:setTextAreaSize({width = 0, height = 0})
Text_26:setFontSize(24)
Text_26:setString([[提示：提供100元以上金额的代充服务]])
Text_26:setLayoutComponentEnabled(true)
Text_26:setName("Text_26")
Text_26:setTag(536)
Text_26:setCascadeColorEnabled(true)
Text_26:setCascadeOpacityEnabled(true)
Text_26:setPosition(475.0000, 130.4688)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_26)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2121)
layout:setPercentWidth(0.4168)
layout:setPercentHeight(0.0390)
layout:setSize({width = 396.0000, height = 24.0000})
layout:setLeftMargin(277.0000)
layout:setRightMargin(277.0000)
layout:setTopMargin(472.5312)
layout:setBottomMargin(118.4688)
Panel_dlcz:addChild(Text_26)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

