--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_base
local Panel_base = ccui.Layout:create()
Panel_base:ignoreContentAdaptWithSize(false)
Panel_base:setClippingEnabled(false)
Panel_base:setBackGroundColorOpacity(102)
Panel_base:setTouchEnabled(true);
Panel_base:setLayoutComponentEnabled(true)
Panel_base:setName("Panel_base")
Panel_base:setTag(334)
Panel_base:setCascadeColorEnabled(true)
Panel_base:setCascadeOpacityEnabled(true)
Panel_base:setAnchorPoint(0.5000, 0.5000)
Panel_base:setPosition(640.0000, 361.1840)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_base)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5016)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setTopMargin(-1.1840)
layout:setBottomMargin(1.1840)
Layer:addChild(Panel_base)

--Create FileNode_1
innerCSD = require("PublicTopInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_1 = innerProject.root
FileNode_1.animation = innerProject.animation
FileNode_1:setName("FileNode_1")
FileNode_1:setTag(355)
FileNode_1:setCascadeColorEnabled(true)
FileNode_1:setCascadeOpacityEnabled(true)
FileNode_1:setPosition(0.0000, 720.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(1.0000)
layout:setRightMargin(1280.0000)
layout:setBottomMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_1:runAction(innerProject.animation)
Panel_base:addChild(FileNode_1)

--Create Image_51
local Image_51 = ccui.ImageView:create()
Image_51:ignoreContentAdaptWithSize(false)
Image_51:loadTexture("hall_res/tongyong/bb_ty_zuodi.png",0)
Image_51:setLayoutComponentEnabled(true)
Image_51:setName("Image_51")
Image_51:setTag(182)
Image_51:setCascadeColorEnabled(true)
Image_51:setCascadeOpacityEnabled(true)
Image_51:setAnchorPoint(0.0000, 0.5000)
Image_51:setPosition(0.0000, 312.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_51)
layout:setPositionPercentY(0.4333)
layout:setPercentWidth(0.2047)
layout:setPercentHeight(0.8861)
layout:setSize({width = 262.0000, height = 638.0000})
layout:setRightMargin(1018.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(-7.0000)
Panel_base:addChild(Image_51)

--Create view_btn_listview
local view_btn_listview = ccui.ListView:create()
view_btn_listview:setItemsMargin(8)
view_btn_listview:setDirection(1)
view_btn_listview:setGravity(0)
view_btn_listview:ignoreContentAdaptWithSize(false)
view_btn_listview:setClippingEnabled(true)
view_btn_listview:setBackGroundColorOpacity(102)
view_btn_listview:setLayoutComponentEnabled(true)
view_btn_listview:setName("view_btn_listview")
view_btn_listview:setTag(581)
view_btn_listview:setCascadeColorEnabled(true)
view_btn_listview:setCascadeOpacityEnabled(true)
view_btn_listview:setAnchorPoint(0.0000, 1.0000)
view_btn_listview:setPosition(-1.4260, 625.0894)
layout = ccui.LayoutComponent:bindLayoutComponent(view_btn_listview)
layout:setPositionPercentX(-0.0011)
layout:setPositionPercentY(0.8682)
layout:setPercentWidth(0.2469)
layout:setPercentHeight(0.8194)
layout:setSize({width = 316.0000, height = 590.0000})
layout:setLeftMargin(-1.4260)
layout:setRightMargin(965.4260)
layout:setTopMargin(94.9106)
layout:setBottomMargin(35.0894)
Panel_base:addChild(view_btn_listview)

--Create btn_zfb
local btn_zfb = ccui.Button:create()
btn_zfb:ignoreContentAdaptWithSize(false)
btn_zfb:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_zhifubao1.png",0)
btn_zfb:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_zhifubao.png",0)
btn_zfb:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_zhifubao.png",0)
btn_zfb:setTitleFontSize(14)
btn_zfb:setTitleColor({r = 65, g = 65, b = 70})
btn_zfb:setScale9Enabled(true)
btn_zfb:setCapInsets({x = 15, y = 11, width = 240, height = 58})
btn_zfb:setLayoutComponentEnabled(true)
btn_zfb:setName("btn_zfb")
btn_zfb:setTag(337)
btn_zfb:setCascadeColorEnabled(true)
btn_zfb:setCascadeOpacityEnabled(true)
btn_zfb:setPosition(135.0000, 550.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_zfb)
layout:setPositionPercentX(0.4272)
layout:setPositionPercentY(0.9322)
layout:setPercentWidth(0.8544)
layout:setPercentHeight(0.1356)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(46.0000)
layout:setBottomMargin(510.0000)
view_btn_listview:pushBackCustomItem(btn_zfb)

--Create btn_wx
local btn_wx = ccui.Button:create()
btn_wx:ignoreContentAdaptWithSize(false)
btn_wx:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_weixin1.png",0)
btn_wx:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_weixin.png",0)
btn_wx:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_weixin.png",0)
btn_wx:setTitleFontSize(14)
btn_wx:setTitleColor({r = 65, g = 65, b = 70})
btn_wx:setScale9Enabled(true)
btn_wx:setCapInsets({x = 15, y = 11, width = 240, height = 58})
btn_wx:setLayoutComponentEnabled(true)
btn_wx:setName("btn_wx")
btn_wx:setLocalZOrder(1)
btn_wx:setTag(338)
btn_wx:setCascadeColorEnabled(true)
btn_wx:setCascadeOpacityEnabled(true)
btn_wx:setPosition(135.0000, 462.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_wx)
layout:setPositionPercentX(0.4272)
layout:setPositionPercentY(0.7831)
layout:setPercentWidth(0.8544)
layout:setPercentHeight(0.1356)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(46.0000)
layout:setTopMargin(88.0000)
layout:setBottomMargin(422.0000)
view_btn_listview:pushBackCustomItem(btn_wx)

--Create btn_zzzf
local btn_zzzf = ccui.Button:create()
btn_zzzf:ignoreContentAdaptWithSize(false)
btn_zzzf:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_zzzf1.png",0)
btn_zzzf:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_zzzf.png",0)
btn_zzzf:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_zzzf.png",0)
btn_zzzf:setTitleFontSize(14)
btn_zzzf:setTitleColor({r = 65, g = 65, b = 70})
btn_zzzf:setScale9Enabled(true)
btn_zzzf:setCapInsets({x = 15, y = 11, width = 240, height = 58})
btn_zzzf:setLayoutComponentEnabled(true)
btn_zzzf:setName("btn_zzzf")
btn_zzzf:setLocalZOrder(2)
btn_zzzf:setTag(11)
btn_zzzf:setCascadeColorEnabled(true)
btn_zzzf:setCascadeOpacityEnabled(true)
btn_zzzf:setPosition(135.0000, 374.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_zzzf)
layout:setPositionPercentX(0.4272)
layout:setPositionPercentY(0.6339)
layout:setPercentWidth(0.8544)
layout:setPercentHeight(0.1356)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(46.0000)
layout:setTopMargin(176.0000)
layout:setBottomMargin(334.0000)
view_btn_listview:pushBackCustomItem(btn_zzzf)

--Create btn_dlcz
local btn_dlcz = ccui.Button:create()
btn_dlcz:ignoreContentAdaptWithSize(false)
btn_dlcz:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_dailizchongzhi1.png",0)
btn_dlcz:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_dailizchongzhi.png",0)
btn_dlcz:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_dailizchongzhi.png",0)
btn_dlcz:setTitleFontSize(14)
btn_dlcz:setTitleColor({r = 65, g = 65, b = 70})
btn_dlcz:setScale9Enabled(true)
btn_dlcz:setCapInsets({x = 15, y = 11, width = 240, height = 58})
btn_dlcz:setLayoutComponentEnabled(true)
btn_dlcz:setName("btn_dlcz")
btn_dlcz:setLocalZOrder(3)
btn_dlcz:setTag(339)
btn_dlcz:setCascadeColorEnabled(true)
btn_dlcz:setCascadeOpacityEnabled(true)
btn_dlcz:setPosition(135.0000, 286.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_dlcz)
layout:setPositionPercentX(0.4272)
layout:setPositionPercentY(0.4847)
layout:setPercentWidth(0.8544)
layout:setPercentHeight(0.1356)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(46.0000)
layout:setTopMargin(264.0000)
layout:setBottomMargin(246.0000)
view_btn_listview:pushBackCustomItem(btn_dlcz)

--Create btn_dlzs
local btn_dlzs = ccui.Button:create()
btn_dlzs:ignoreContentAdaptWithSize(false)
btn_dlzs:loadTextureNormal("hall_res/bank_new/baobo_popupview_button_dailizhaoshan1.png",0)
btn_dlzs:loadTexturePressed("hall_res/bank_new/baobo_popupview_button_dailizhaoshan.png",0)
btn_dlzs:loadTextureDisabled("hall_res/bank_new/baobo_popupview_button_dailizhaoshan.png",0)
btn_dlzs:setTitleFontSize(14)
btn_dlzs:setTitleColor({r = 65, g = 65, b = 70})
btn_dlzs:setScale9Enabled(true)
btn_dlzs:setCapInsets({x = 15, y = 11, width = 240, height = 58})
btn_dlzs:setLayoutComponentEnabled(true)
btn_dlzs:setName("btn_dlzs")
btn_dlzs:setLocalZOrder(4)
btn_dlzs:setTag(340)
btn_dlzs:setCascadeColorEnabled(true)
btn_dlzs:setCascadeOpacityEnabled(true)
btn_dlzs:setPosition(135.0000, 198.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_dlzs)
layout:setPositionPercentX(0.4272)
layout:setPositionPercentY(0.3356)
layout:setPercentWidth(0.8544)
layout:setPercentHeight(0.1356)
layout:setSize({width = 270.0000, height = 80.0000})
layout:setRightMargin(46.0000)
layout:setTopMargin(352.0000)
layout:setBottomMargin(158.0000)
view_btn_listview:pushBackCustomItem(btn_dlzs)

--Create sub_view_parent
local sub_view_parent = ccui.Layout:create()
sub_view_parent:ignoreContentAdaptWithSize(false)
sub_view_parent:setClippingEnabled(false)
sub_view_parent:setBackGroundColorOpacity(102)
sub_view_parent:setTouchEnabled(true);
sub_view_parent:setLayoutComponentEnabled(true)
sub_view_parent:setName("sub_view_parent")
sub_view_parent:setTag(585)
sub_view_parent:setCascadeColorEnabled(true)
sub_view_parent:setCascadeOpacityEnabled(true)
sub_view_parent:setAnchorPoint(0.0000, 1.0000)
sub_view_parent:setPosition(325.7400, 624.3116)
layout = ccui.LayoutComponent:bindLayoutComponent(sub_view_parent)
layout:setPositionPercentX(0.2545)
layout:setPositionPercentY(0.8671)
layout:setPercentWidth(0.7422)
layout:setPercentHeight(0.8542)
layout:setSize({width = 950.0000, height = 615.0000})
layout:setLeftMargin(325.7400)
layout:setRightMargin(4.2600)
layout:setTopMargin(95.6884)
layout:setBottomMargin(9.3116)
Panel_base:addChild(sub_view_parent)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

