--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(128)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(10)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create alertView
local alertView = ccui.Layout:create()
alertView:ignoreContentAdaptWithSize(false)
alertView:setClippingEnabled(false)
alertView:setBackGroundColorOpacity(102)
alertView:setTouchEnabled(true);
alertView:setLayoutComponentEnabled(true)
alertView:setName("alertView")
alertView:setTag(12)
alertView:setCascadeColorEnabled(true)
alertView:setCascadeOpacityEnabled(true)
alertView:setAnchorPoint(0.5000, 0.5000)
alertView:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alertView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Panel_1:addChild(alertView)

--Create head_node
innerCSD = require("PublicTopInfoNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local head_node = innerProject.root
head_node.animation = innerProject.animation
head_node:setName("head_node")
head_node:setTag(403)
head_node:setCascadeColorEnabled(true)
head_node:setCascadeOpacityEnabled(true)
head_node:setPosition(0.0029, 720.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(head_node)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(1.0000)
layout:setLeftMargin(0.0029)
layout:setRightMargin(1279.9970)
layout:setBottomMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
head_node:runAction(innerProject.animation)
alertView:addChild(head_node)

--Create roomListView
local roomListView = ccui.ListView:create()
roomListView:setDirection(2)
roomListView:setGravity(3)
roomListView:ignoreContentAdaptWithSize(false)
roomListView:setClippingEnabled(true)
roomListView:setBackGroundColorOpacity(102)
roomListView:setLayoutComponentEnabled(true)
roomListView:setName("roomListView")
roomListView:setTag(24)
roomListView:setCascadeColorEnabled(true)
roomListView:setCascadeOpacityEnabled(true)
roomListView:setPosition(0.0000, 129.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(roomListView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentY(0.1792)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6250)
layout:setSize({width = 1280.0000, height = 450.0000})
layout:setTopMargin(141.0000)
layout:setBottomMargin(129.0000)
alertView:addChild(roomListView)

--Create defaultItemNode
local defaultItemNode = ccui.Layout:create()
defaultItemNode:ignoreContentAdaptWithSize(false)
defaultItemNode:setClippingEnabled(false)
defaultItemNode:setBackGroundColorOpacity(102)
defaultItemNode:setTouchEnabled(true);
defaultItemNode:setLayoutComponentEnabled(true)
defaultItemNode:setName("defaultItemNode")
defaultItemNode:setTag(152)
defaultItemNode:setCascadeColorEnabled(true)
defaultItemNode:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(defaultItemNode)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 450.0000})
roomListView:pushBackCustomItem(defaultItemNode)

--Create btn_quickStart
local btn_quickStart = ccui.Button:create()
btn_quickStart:ignoreContentAdaptWithSize(false)
btn_quickStart:loadTextureNormal("hall_res/game_select/bb_fc_ddz_normal.png",0)
btn_quickStart:loadTexturePressed("hall_res/game_select/bb_fc_ddz_pressed.png",0)
btn_quickStart:loadTextureDisabled("hall_res/game_select/bb_fc_ddz_pressed.png",0)
btn_quickStart:setTitleFontSize(14)
btn_quickStart:setTitleColor({r = 65, g = 65, b = 70})
btn_quickStart:setScale9Enabled(true)
btn_quickStart:setCapInsets({x = 15, y = 11, width = 253, height = 73})
btn_quickStart:setLayoutComponentEnabled(true)
btn_quickStart:setName("btn_quickStart")
btn_quickStart:setTag(55)
btn_quickStart:setCascadeColorEnabled(true)
btn_quickStart:setCascadeOpacityEnabled(true)
btn_quickStart:setAnchorPoint(0.5003, 0.5494)
btn_quickStart:setPosition(635.2640, 64.6567)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_quickStart)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4963)
layout:setPositionPercentY(0.0898)
layout:setPercentWidth(0.2211)
layout:setPercentHeight(0.1319)
layout:setSize({width = 283.0000, height = 95.0000})
layout:setLeftMargin(493.6791)
layout:setRightMargin(503.3209)
layout:setTopMargin(612.5363)
layout:setBottomMargin(12.4637)
alertView:addChild(btn_quickStart)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

