--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panel_shadow
local panel_shadow = ccui.Layout:create()
panel_shadow:ignoreContentAdaptWithSize(false)
panel_shadow:setClippingEnabled(false)
panel_shadow:setBackGroundColorOpacity(102)
panel_shadow:setTouchEnabled(true);
panel_shadow:setLayoutComponentEnabled(true)
panel_shadow:setName("panel_shadow")
panel_shadow:setTag(448)
panel_shadow:setCascadeColorEnabled(true)
panel_shadow:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_shadow)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panel_shadow)

--Create shadow_bg
local shadow_bg = ccui.ImageView:create()
shadow_bg:ignoreContentAdaptWithSize(false)
shadow_bg:loadTexture("game_res/icon_background.png",0)
shadow_bg:setLayoutComponentEnabled(true)
shadow_bg:setName("shadow_bg")
shadow_bg:setTag(449)
shadow_bg:setCascadeColorEnabled(true)
shadow_bg:setCascadeOpacityEnabled(true)
shadow_bg:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shadow_bg)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
panel_shadow:addChild(shadow_bg)

--Create shadow_bg_1
local shadow_bg_1 = ccui.ImageView:create()
shadow_bg_1:ignoreContentAdaptWithSize(false)
shadow_bg_1:loadTexture("game_res/icon_desktop.png",0)
shadow_bg_1:setLayoutComponentEnabled(true)
shadow_bg_1:setName("shadow_bg_1")
shadow_bg_1:setTag(450)
shadow_bg_1:setCascadeColorEnabled(true)
shadow_bg_1:setCascadeOpacityEnabled(true)
shadow_bg_1:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(shadow_bg_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6903)
layout:setSize({width = 1280.0000, height = 497.0000})
layout:setTopMargin(223.0000)
panel_shadow:addChild(shadow_bg_1)

--Create shadowTips
local shadowTips = ccui.ImageView:create()
shadowTips:ignoreContentAdaptWithSize(false)
shadowTips:loadTexture("game_res/match.png",0)
shadowTips:setLayoutComponentEnabled(true)
shadowTips:setName("shadowTips")
shadowTips:setTag(451)
shadowTips:setCascadeColorEnabled(true)
shadowTips:setCascadeOpacityEnabled(true)
shadowTips:setPosition(601.6000, 343.3900)
layout = ccui.LayoutComponent:bindLayoutComponent(shadowTips)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4700)
layout:setPositionPercentY(0.4769)
layout:setPercentWidth(0.2188)
layout:setPercentHeight(0.1250)
layout:setSize({width = 280.0000, height = 90.0000})
layout:setLeftMargin(461.6000)
layout:setRightMargin(538.4000)
layout:setTopMargin(331.6100)
layout:setBottomMargin(298.3900)
panel_shadow:addChild(shadowTips)

--Create shadow_Image_1
local shadow_Image_1 = ccui.ImageView:create()
shadow_Image_1:ignoreContentAdaptWithSize(false)
shadow_Image_1:loadTexture("game_res/dian_dian.png",0)
shadow_Image_1:setLayoutComponentEnabled(true)
shadow_Image_1:setName("shadow_Image_1")
shadow_Image_1:setTag(452)
shadow_Image_1:setCascadeColorEnabled(true)
shadow_Image_1:setCascadeOpacityEnabled(true)
shadow_Image_1:setPosition(771.0759, 340.0205)
layout = ccui.LayoutComponent:bindLayoutComponent(shadow_Image_1)
layout:setPositionPercentX(0.6024)
layout:setPositionPercentY(0.4723)
layout:setPercentWidth(0.0203)
layout:setPercentHeight(0.0417)
layout:setSize({width = 26.0000, height = 30.0000})
layout:setLeftMargin(758.0759)
layout:setRightMargin(495.9241)
layout:setTopMargin(364.9795)
layout:setBottomMargin(325.0205)
panel_shadow:addChild(shadow_Image_1)

--Create shadow_Image_2
local shadow_Image_2 = ccui.ImageView:create()
shadow_Image_2:ignoreContentAdaptWithSize(false)
shadow_Image_2:loadTexture("game_res/dian_dian.png",0)
shadow_Image_2:setLayoutComponentEnabled(true)
shadow_Image_2:setName("shadow_Image_2")
shadow_Image_2:setTag(453)
shadow_Image_2:setCascadeColorEnabled(true)
shadow_Image_2:setCascadeOpacityEnabled(true)
shadow_Image_2:setPosition(818.0762, 340.0205)
layout = ccui.LayoutComponent:bindLayoutComponent(shadow_Image_2)
layout:setPositionPercentX(0.6391)
layout:setPositionPercentY(0.4723)
layout:setPercentWidth(0.0203)
layout:setPercentHeight(0.0417)
layout:setSize({width = 26.0000, height = 30.0000})
layout:setLeftMargin(805.0762)
layout:setRightMargin(448.9238)
layout:setTopMargin(364.9795)
layout:setBottomMargin(325.0205)
panel_shadow:addChild(shadow_Image_2)

--Create shadow_Image_3
local shadow_Image_3 = ccui.ImageView:create()
shadow_Image_3:ignoreContentAdaptWithSize(false)
shadow_Image_3:loadTexture("game_res/dian_dian.png",0)
shadow_Image_3:setLayoutComponentEnabled(true)
shadow_Image_3:setName("shadow_Image_3")
shadow_Image_3:setTag(454)
shadow_Image_3:setCascadeColorEnabled(true)
shadow_Image_3:setCascadeOpacityEnabled(true)
shadow_Image_3:setPosition(865.0775, 340.0205)
layout = ccui.LayoutComponent:bindLayoutComponent(shadow_Image_3)
layout:setPositionPercentX(0.6758)
layout:setPositionPercentY(0.4723)
layout:setPercentWidth(0.0203)
layout:setPercentHeight(0.0417)
layout:setSize({width = 26.0000, height = 30.0000})
layout:setLeftMargin(852.0775)
layout:setRightMargin(401.9225)
layout:setTopMargin(364.9795)
layout:setBottomMargin(325.0205)
panel_shadow:addChild(shadow_Image_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

