--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panel_TimeoutWait
local panel_TimeoutWait = ccui.Layout:create()
panel_TimeoutWait:ignoreContentAdaptWithSize(false)
panel_TimeoutWait:setClippingEnabled(false)
panel_TimeoutWait:setBackGroundColorType(1)
panel_TimeoutWait:setBackGroundColor({r = 0, g = 0, b = 0})
panel_TimeoutWait:setBackGroundColorOpacity(102)
panel_TimeoutWait:setTouchEnabled(true);
panel_TimeoutWait:setLayoutComponentEnabled(true)
panel_TimeoutWait:setName("panel_TimeoutWait")
panel_TimeoutWait:setTag(374)
panel_TimeoutWait:setCascadeColorEnabled(true)
panel_TimeoutWait:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_TimeoutWait)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(panel_TimeoutWait)

--Create but_touch
local but_touch = ccui.Button:create()
but_touch:ignoreContentAdaptWithSize(false)
but_touch:setTitleFontSize(14)
but_touch:setTitleColor({r = 65, g = 65, b = 70})
but_touch:setScale9Enabled(true)
but_touch:setCapInsets({x = -15, y = -4, width = 30, height = 8})
but_touch:setLayoutComponentEnabled(true)
but_touch:setName("but_touch")
but_touch:setTag(375)
but_touch:setCascadeColorEnabled(true)
but_touch:setCascadeOpacityEnabled(true)
but_touch:setAnchorPoint(0.0000, 0.0000)
but_touch:setPosition(5.6317, 6.7287)
layout = ccui.LayoutComponent:bindLayoutComponent(but_touch)
layout:setPositionPercentX(0.0044)
layout:setPositionPercentY(0.0093)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(5.6317)
layout:setRightMargin(-5.6317)
layout:setTopMargin(-6.7287)
layout:setBottomMargin(6.7287)
panel_TimeoutWait:addChild(but_touch)

--Create text_tips
local text_tips = ccui.Text:create()
text_tips:ignoreContentAdaptWithSize(true)
text_tips:setTextAreaSize({width = 0, height = 0})
text_tips:setFontSize(36)
text_tips:setString([[有玩家掉线...请等待重连]])
text_tips:setLayoutComponentEnabled(true)
text_tips:setName("text_tips")
text_tips:setTag(376)
text_tips:setCascadeColorEnabled(true)
text_tips:setCascadeOpacityEnabled(true)
text_tips:setPosition(699.8986, 399.2601)
layout = ccui.LayoutComponent:bindLayoutComponent(text_tips)
layout:setPositionPercentX(0.5468)
layout:setPositionPercentY(0.5545)
layout:setPercentWidth(0.3234)
layout:setPercentHeight(0.0500)
layout:setSize({width = 414.0000, height = 36.0000})
layout:setLeftMargin(492.8986)
layout:setRightMargin(373.1014)
layout:setTopMargin(302.7399)
layout:setBottomMargin(381.2601)
panel_TimeoutWait:addChild(text_tips)

--Create text_outTime
local text_outTime = ccui.Text:create()
text_outTime:ignoreContentAdaptWithSize(true)
text_outTime:setTextAreaSize({width = 0, height = 0})
text_outTime:setFontSize(30)
text_outTime:setString([[0]])
text_outTime:setLayoutComponentEnabled(true)
text_outTime:setName("text_outTime")
text_outTime:setTag(377)
text_outTime:setCascadeColorEnabled(true)
text_outTime:setCascadeOpacityEnabled(true)
text_outTime:setPosition(664.1818, 354.8939)
layout = ccui.LayoutComponent:bindLayoutComponent(text_outTime)
layout:setPositionPercentX(0.5189)
layout:setPositionPercentY(0.4929)
layout:setPercentWidth(0.0117)
layout:setPercentHeight(0.0417)
layout:setSize({width = 15.0000, height = 30.0000})
layout:setLeftMargin(656.6818)
layout:setRightMargin(608.3182)
layout:setTopMargin(350.1061)
layout:setBottomMargin(339.8939)
panel_TimeoutWait:addChild(text_outTime)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

