--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_DeviceUtil
local Panel_DeviceUtil = ccui.Layout:create()
Panel_DeviceUtil:ignoreContentAdaptWithSize(false)
Panel_DeviceUtil:setClippingEnabled(false)
Panel_DeviceUtil:setBackGroundColorType(1)
Panel_DeviceUtil:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_DeviceUtil:setBackGroundColorOpacity(102)
Panel_DeviceUtil:setTouchEnabled(true);
Panel_DeviceUtil:setLayoutComponentEnabled(true)
Panel_DeviceUtil:setName("Panel_DeviceUtil")
Panel_DeviceUtil:setTag(395)
Panel_DeviceUtil:setCascadeColorEnabled(true)
Panel_DeviceUtil:setCascadeOpacityEnabled(true)
Panel_DeviceUtil:setPosition(43.7307, -23.6027)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_DeviceUtil)
layout:setLeftMargin(43.7307)
layout:setRightMargin(-43.7307)
layout:setTopMargin(23.6027)
layout:setBottomMargin(-23.6027)
Node:addChild(Panel_DeviceUtil)

--Create Image_5
local Image_5 = ccui.ImageView:create()
Image_5:ignoreContentAdaptWithSize(false)
Image_5:loadTexture("game_res/di.png",0)
Image_5:setLayoutComponentEnabled(true)
Image_5:setName("Image_5")
Image_5:setTag(396)
Image_5:setCascadeColorEnabled(true)
Image_5:setCascadeOpacityEnabled(true)
Image_5:setPosition(-0.1725, -0.1335)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_5)
layout:setSize({width = 81.0000, height = 44.0000})
layout:setLeftMargin(-40.6725)
layout:setRightMargin(-40.3275)
layout:setTopMargin(-21.8665)
layout:setBottomMargin(-22.1335)
Panel_DeviceUtil:addChild(Image_5)

--Create dianci_bg
local dianci_bg = ccui.ImageView:create()
dianci_bg:ignoreContentAdaptWithSize(false)
dianci_bg:loadTexture("game_res/dianchi.png",0)
dianci_bg:setLayoutComponentEnabled(true)
dianci_bg:setName("dianci_bg")
dianci_bg:setTag(397)
dianci_bg:setCascadeColorEnabled(true)
dianci_bg:setCascadeOpacityEnabled(true)
dianci_bg:setPosition(54.5570, 22.3963)
layout = ccui.LayoutComponent:bindLayoutComponent(dianci_bg)
layout:setPositionPercentX(0.6735)
layout:setPositionPercentY(0.5090)
layout:setPercentWidth(0.5309)
layout:setPercentHeight(0.5455)
layout:setSize({width = 43.0000, height = 24.0000})
layout:setLeftMargin(33.0570)
layout:setRightMargin(4.9430)
layout:setTopMargin(9.6037)
layout:setBottomMargin(10.3963)
Image_5:addChild(dianci_bg)

--Create dianliang
local dianliang = ccui.ImageView:create()
dianliang:ignoreContentAdaptWithSize(false)
dianliang:loadTexture("game_res/dianliangtiao.png",0)
dianliang:setLayoutComponentEnabled(true)
dianliang:setName("dianliang")
dianliang:setTag(398)
dianliang:setCascadeColorEnabled(true)
dianliang:setCascadeOpacityEnabled(true)
dianliang:setAnchorPoint(0.0000, 0.5000)
dianliang:setPosition(5.9254, 12.2400)
layout = ccui.LayoutComponent:bindLayoutComponent(dianliang)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1378)
layout:setPositionPercentY(0.5100)
layout:setPercentWidth(0.6744)
layout:setPercentHeight(0.5000)
layout:setSize({width = 29.0000, height = 12.0000})
layout:setLeftMargin(5.9254)
layout:setRightMargin(8.0746)
layout:setTopMargin(5.7600)
layout:setBottomMargin(6.2400)
dianci_bg:addChild(dianliang)

--Create chongdian
local chongdian = ccui.ImageView:create()
chongdian:ignoreContentAdaptWithSize(false)
chongdian:loadTexture("game_res/chongdian.png",0)
chongdian:setLayoutComponentEnabled(true)
chongdian:setName("chongdian")
chongdian:setTag(399)
chongdian:setCascadeColorEnabled(true)
chongdian:setCascadeOpacityEnabled(true)
chongdian:setPosition(21.2636, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(chongdian)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4945)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4186)
layout:setPercentHeight(0.5000)
layout:setSize({width = 18.0000, height = 12.0000})
layout:setLeftMargin(12.2636)
layout:setRightMargin(12.7364)
layout:setTopMargin(6.0000)
layout:setBottomMargin(6.0000)
dianci_bg:addChild(chongdian)

--Create wifi_bg
local wifi_bg = ccui.ImageView:create()
wifi_bg:ignoreContentAdaptWithSize(false)
wifi_bg:loadTexture("game_res/wifi.png",0)
wifi_bg:setLayoutComponentEnabled(true)
wifi_bg:setName("wifi_bg")
wifi_bg:setTag(400)
wifi_bg:setCascadeColorEnabled(true)
wifi_bg:setCascadeOpacityEnabled(true)
wifi_bg:setPosition(16.5854, 22.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(wifi_bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2048)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3457)
layout:setPercentHeight(0.4318)
layout:setSize({width = 28.0000, height = 19.0000})
layout:setLeftMargin(2.5854)
layout:setRightMargin(50.4146)
layout:setTopMargin(12.5000)
layout:setBottomMargin(12.5000)
Image_5:addChild(wifi_bg)

--Create wifi_1
local wifi_1 = ccui.ImageView:create()
wifi_1:ignoreContentAdaptWithSize(false)
wifi_1:loadTexture("game_res/WiFi1.png",0)
wifi_1:setLayoutComponentEnabled(true)
wifi_1:setName("wifi_1")
wifi_1:setTag(401)
wifi_1:setCascadeColorEnabled(true)
wifi_1:setCascadeOpacityEnabled(true)
wifi_1:setPosition(14.0000, 1.1000)
layout = ccui.LayoutComponent:bindLayoutComponent(wifi_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0579)
layout:setPercentWidth(0.1429)
layout:setPercentHeight(0.2105)
layout:setSize({width = 4.0000, height = 4.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(12.0000)
layout:setTopMargin(15.9000)
layout:setBottomMargin(-0.9000)
wifi_bg:addChild(wifi_1)

--Create wifi_2
local wifi_2 = ccui.ImageView:create()
wifi_2:ignoreContentAdaptWithSize(false)
wifi_2:loadTexture("game_res/wifi2.png",0)
wifi_2:setLayoutComponentEnabled(true)
wifi_2:setName("wifi_2")
wifi_2:setTag(402)
wifi_2:setCascadeColorEnabled(true)
wifi_2:setCascadeOpacityEnabled(true)
wifi_2:setPosition(14.0000, 9.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(wifi_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.6429)
layout:setPercentHeight(0.4211)
layout:setSize({width = 18.0000, height = 8.0000})
layout:setLeftMargin(5.0000)
layout:setRightMargin(5.0000)
layout:setTopMargin(6.0000)
layout:setBottomMargin(5.0000)
wifi_bg:addChild(wifi_2)

--Create wifi_3
local wifi_3 = ccui.ImageView:create()
wifi_3:ignoreContentAdaptWithSize(false)
wifi_3:loadTexture("game_res/wifi3.png",0)
wifi_3:setLayoutComponentEnabled(true)
wifi_3:setName("wifi_3")
wifi_3:setTag(403)
wifi_3:setCascadeColorEnabled(true)
wifi_3:setCascadeOpacityEnabled(true)
wifi_3:setPosition(14.0000, 15.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(wifi_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7895)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4737)
layout:setSize({width = 28.0000, height = 9.0000})
layout:setTopMargin(-0.5000)
layout:setBottomMargin(10.5000)
wifi_bg:addChild(wifi_3)

--Create liuliang_bg
local liuliang_bg = ccui.ImageView:create()
liuliang_bg:ignoreContentAdaptWithSize(false)
liuliang_bg:loadTexture("game_res/yidongshuju.png",0)
liuliang_bg:setLayoutComponentEnabled(true)
liuliang_bg:setName("liuliang_bg")
liuliang_bg:setTag(404)
liuliang_bg:setCascadeColorEnabled(true)
liuliang_bg:setCascadeOpacityEnabled(true)
liuliang_bg:setVisible(false)
liuliang_bg:setPosition(17.4514, 22.7098)
layout = ccui.LayoutComponent:bindLayoutComponent(liuliang_bg)
layout:setPositionPercentX(0.2154)
layout:setPositionPercentY(0.5161)
layout:setPercentWidth(0.2469)
layout:setPercentHeight(0.5455)
layout:setSize({width = 20.0000, height = 24.0000})
layout:setLeftMargin(7.4514)
layout:setRightMargin(53.5486)
layout:setTopMargin(9.2902)
layout:setBottomMargin(10.7098)
Image_5:addChild(liuliang_bg)

--Create liuliang_1
local liuliang_1 = ccui.ImageView:create()
liuliang_1:ignoreContentAdaptWithSize(false)
liuliang_1:loadTexture("game_res/xinhao1.png",0)
liuliang_1:setLayoutComponentEnabled(true)
liuliang_1:setName("liuliang_1")
liuliang_1:setTag(405)
liuliang_1:setCascadeColorEnabled(true)
liuliang_1:setCascadeOpacityEnabled(true)
liuliang_1:setPosition(3.0000, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(liuliang_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1500)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 8.0000, height = 24.0000})
layout:setLeftMargin(-1.0000)
layout:setRightMargin(13.0000)
liuliang_bg:addChild(liuliang_1)

--Create liuliang_2
local liuliang_2 = ccui.ImageView:create()
liuliang_2:ignoreContentAdaptWithSize(false)
liuliang_2:loadTexture("game_res/xinhao2.png",0)
liuliang_2:setLayoutComponentEnabled(true)
liuliang_2:setName("liuliang_2")
liuliang_2:setTag(406)
liuliang_2:setCascadeColorEnabled(true)
liuliang_2:setCascadeOpacityEnabled(true)
liuliang_2:setPosition(16.0000, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(liuliang_2)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.8000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 8.0000, height = 24.0000})
layout:setLeftMargin(12.0000)
liuliang_bg:addChild(liuliang_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

