--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("game_res/desk/renwudi.png",0)
Image_bg:setTouchEnabled(true);
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(15)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(-148.7351, -4.7289)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 299.0000, height = 128.0000})
layout:setLeftMargin(-298.2351)
layout:setRightMargin(-0.7649)
layout:setTopMargin(-59.2711)
layout:setBottomMargin(-68.7289)
Node:addChild(Image_bg)

--Create Image_task_icon
local Image_task_icon = ccui.ImageView:create()
Image_task_icon:ignoreContentAdaptWithSize(false)
Image_task_icon:loadTexture("game_res/desk/renwu.png",0)
Image_task_icon:setLayoutComponentEnabled(true)
Image_task_icon:setName("Image_task_icon")
Image_task_icon:setTag(16)
Image_task_icon:setCascadeColorEnabled(true)
Image_task_icon:setCascadeOpacityEnabled(true)
Image_task_icon:setPosition(290.1706, 64.1666)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_task_icon)
layout:setPositionPercentX(0.9705)
layout:setPositionPercentY(0.5013)
layout:setPercentWidth(0.1171)
layout:setPercentHeight(0.4141)
layout:setSize({width = 35.0000, height = 53.0000})
layout:setLeftMargin(272.6706)
layout:setRightMargin(-8.6706)
layout:setTopMargin(37.3334)
layout:setBottomMargin(37.6666)
Image_bg:addChild(Image_task_icon)

--Create AtlasLabel_winNumber
local AtlasLabel_winNumber = ccui.TextAtlas:create([[0]],
													"game_res/desk/renwushuzi.png",
													18,
													31,
													"/")
AtlasLabel_winNumber:setLayoutComponentEnabled(true)
AtlasLabel_winNumber:setName("AtlasLabel_winNumber")
AtlasLabel_winNumber:setTag(28)
AtlasLabel_winNumber:setCascadeColorEnabled(true)
AtlasLabel_winNumber:setCascadeOpacityEnabled(true)
AtlasLabel_winNumber:setAnchorPoint(0.0000, 0.5000)
AtlasLabel_winNumber:setPosition(228.5138, 67.7702)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_winNumber)
layout:setPositionPercentX(0.7643)
layout:setPositionPercentY(0.5295)
layout:setPercentWidth(0.0602)
layout:setPercentHeight(0.2422)
layout:setSize({width = 18.0000, height = 31.0000})
layout:setLeftMargin(228.5138)
layout:setRightMargin(52.4862)
layout:setTopMargin(44.7298)
layout:setBottomMargin(52.2702)
Image_bg:addChild(AtlasLabel_winNumber)

--Create Image_tag
local Image_tag = ccui.ImageView:create()
Image_tag:ignoreContentAdaptWithSize(false)
Image_tag:loadTexture("game_res/desk/hu3.png",0)
Image_tag:setLayoutComponentEnabled(true)
Image_tag:setName("Image_tag")
Image_tag:setTag(29)
Image_tag:setCascadeColorEnabled(true)
Image_tag:setCascadeOpacityEnabled(true)
Image_tag:setPosition(61.1075, 68.4837)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tag)
layout:setPositionPercentX(0.2044)
layout:setPositionPercentY(0.5350)
layout:setPercentWidth(0.1371)
layout:setPercentHeight(0.2578)
layout:setSize({width = 41.0000, height = 33.0000})
layout:setLeftMargin(40.6075)
layout:setRightMargin(217.3925)
layout:setTopMargin(43.0163)
layout:setBottomMargin(51.9837)
Image_bg:addChild(Image_tag)

--Create Image_complete
local Image_complete = ccui.ImageView:create()
Image_complete:ignoreContentAdaptWithSize(false)
Image_complete:loadTexture("game_res/desk/wancheng.png",0)
Image_complete:setLayoutComponentEnabled(true)
Image_complete:setName("Image_complete")
Image_complete:setTag(38)
Image_complete:setCascadeColorEnabled(true)
Image_complete:setCascadeOpacityEnabled(true)
Image_complete:setPosition(343.9325, 64.2984)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_complete)
layout:setPositionPercentX(1.1503)
layout:setPositionPercentY(0.5023)
layout:setPercentWidth(0.1672)
layout:setPercentHeight(0.8125)
layout:setSize({width = 50.0000, height = 104.0000})
layout:setLeftMargin(318.9325)
layout:setRightMargin(-69.9325)
layout:setTopMargin(11.7016)
layout:setBottomMargin(12.2984)
Image_bg:addChild(Image_complete)

--Create FileNode_card
innerCSD = require("TmjCardNodeCCS")
innerProject = innerCSD.create(callBackProvider)
local FileNode_card = innerProject.root
FileNode_card.animation = innerProject.animation
FileNode_card:setName("FileNode_card")
FileNode_card:setTag(53)
FileNode_card:setCascadeColorEnabled(true)
FileNode_card:setCascadeOpacityEnabled(true)
FileNode_card:setPosition(108.5761, 63.3433)
FileNode_card:setScaleX(0.6000)
FileNode_card:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(FileNode_card)
layout:setPositionPercentX(0.3631)
layout:setPositionPercentY(0.4949)
layout:setLeftMargin(108.5761)
layout:setRightMargin(190.4239)
layout:setTopMargin(64.6567)
layout:setBottomMargin(63.3433)
innerProject.animation:setTimeSpeed(1.0000)
FileNode_card:runAction(innerProject.animation)
Image_bg:addChild(FileNode_card)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

