--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create base_layout
local base_layout = ccui.Layout:create()
base_layout:ignoreContentAdaptWithSize(false)
base_layout:setBackGroundImage("game_res/peilvbiao.png",0)
base_layout:setClippingEnabled(true)
base_layout:setBackGroundColorOpacity(102)
base_layout:setTouchEnabled(true);
base_layout:setLayoutComponentEnabled(true)
base_layout:setName("base_layout")
base_layout:setTag(40)
base_layout:setCascadeColorEnabled(true)
base_layout:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(base_layout)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(base_layout)

--Create ListView_2
local ListView_2 = ccui.ListView:create()
ListView_2:setDirection(1)
ListView_2:setGravity(2)
ListView_2:ignoreContentAdaptWithSize(false)
ListView_2:setClippingEnabled(true)
ListView_2:setBackGroundColorOpacity(102)
ListView_2:setLayoutComponentEnabled(true)
ListView_2:setName("ListView_2")
ListView_2:setTag(41)
ListView_2:setCascadeColorEnabled(true)
ListView_2:setCascadeOpacityEnabled(true)
ListView_2:setPosition(150.8837, 50.7788)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_2)
layout:setPositionPercentX(0.1179)
layout:setPositionPercentY(0.0705)
layout:setPercentWidth(0.7531)
layout:setPercentHeight(0.7611)
layout:setSize({width = 964.0000, height = 548.0000})
layout:setLeftMargin(150.8837)
layout:setRightMargin(165.1163)
layout:setTopMargin(121.2212)
layout:setBottomMargin(50.7788)
base_layout:addChild(ListView_2)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("game_res/guize.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(42)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(482.0000, 452.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9834)
layout:setPercentHeight(1.0000)
layout:setSize({width = 948.0000, height = 904.0000})
layout:setLeftMargin(8.0000)
layout:setRightMargin(8.0000)
ListView_2:pushBackCustomItem(Image_2)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("game_res/gb.png",0)
btn_close:loadTexturePressed("game_res/gb_2.png",0)
btn_close:loadTextureDisabled("game_res/gb_2.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 52, height = 60})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(43)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(1118.5700, 657.2147)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.8739)
layout:setPositionPercentY(0.9128)
layout:setPercentWidth(0.0641)
layout:setPercentHeight(0.1139)
layout:setSize({width = 82.0000, height = 82.0000})
layout:setLeftMargin(1077.5700)
layout:setRightMargin(120.4299)
layout:setTopMargin(21.7853)
layout:setBottomMargin(616.2147)
base_layout:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

